---
  title: "RAF Gesamtnetzwerk"
author: "sws"
date: "11 5 2020"
output: pdf_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Skript Erstellung einfaches Netzwerk

# lädt igraph Bibliothek (ggf. vorher installieren)
library(igraph)


# liest die Edgelist als "el" ein
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",", row.names=NULL)


# zeigt die ersten sechs Zeilen des Datensatzes an
head(el)

# liest die Nodelist mit den Namen ein
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

# zeigt die ersten sechs Zeilen der Nodelist und die Attribute der Nodes an
head(nodes)

# Zwischenschritt verbindet die Edge- und Nodelist zu einer Matrix
raf_matrix <- as.matrix(el)

# zeigt die Matrix an
raf_matrix

# generiert ein igraph-Objekt (dataframe) aus der Matrix, das ungerichtet ist (directed = false)
raf <- graph_from_data_frame(d=raf_matrix, directed=FALSE)

# ruft unser neues igraph-Objekt auf
raf

# stellt die Art der Beziehung farblich da
E(raf)[E(raf)$relationship == " 1"]$color <-"red"
E(raf)[E(raf)$relationship == " 2"]$color <-"darkgreen"
E(raf)[E(raf)$relationship == " 3"]$color <-"blue"
E(raf)[E(raf)$relationship == " 4"]$color <-"yellow"
E(raf)[E(raf)$relationship == " 5"]$color <-"purple"
E(raf)[E(raf)$relationship == " 6"]$color <-"pink"
E(raf)[E(raf)$relationship == " 7"]$color <-"chartreuse"
E(raf)[E(raf)$relationship == " 8"]$color <-"cyan"
E(raf)[E(raf)$relationship == " 9"]$color <-"darkslateblue"
E(raf)[E(raf)$relationship == "10"]$color <-"springgreen" 

# generiert die Standard-Visualisierung des Netzwerks
plot(raf)

degree <- degree(raf)
degree



# einfacher plot
```


```{r fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

#edge.attributes(raf)


plot(raf,
     layout=layout_with_kk,
     vertex.size=5,
     vertex.frame.color=NA,
     main="RAF-Netzwerk mit Edges")

```
```{r Selektion nach Beziehungen}

V(raf)$color <- "white" #färbt die edges weiß

#V(raf)[V(raf)$type == 1]$shape <- "circle" # Personen als Kreise
#V(raf)[V(raf)$type == 2]$shape <- "square" # Aktionen als Quadrate

#Bekanntschaftsnetzwerk:

contact <- subgraph.edges(raf, E(raf)[relationship== " 1"]) 
contact
contact <- simplify(contact, remove.multiple = TRUE)

plot(contact,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(contact), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="red",
     main="Bekanntschafts-Netzwerk")


#Freundschaftsnetzwerk:

friendship <- subgraph.edges(raf, E(raf)[relationship== " 2"]) 
friendship <- simplify(friendship, remove.multiple = TRUE)
friendship

plot(friendship,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(friendship), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="darkgreen",
     main="Freundschafts-Netzwerk")


#Liebesnetzwerk:
love <- subgraph.edges(raf, E(raf)[relationship== " 3"])
love

love <- simplify(love, remove.multiple=TRUE,) #löscht doppelte Beziehungen

plot(love,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(love), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="blue",
     main="Liebesbeziehungs-Netzwerk")

#WG-Netzwerk

wg <- subgraph.edges(raf, E(raf)[relationship== " 4"]) 
wg <- simplify(wg, remove.multiple = TRUE)
wg

plot(wg,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(wg), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="yellow",
     main="Wohnungsgemeinschafts-Netzwerk")

#Haft-Netzwerk

prison <- subgraph.edges(raf, E(raf)[relationship== " 5"]) 
prison <- simplify(prison, remove.multiple = TRUE)
prison

plot(prison,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(prison), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="purple",
     main="Gemeinsame Haft Netzwerk")

#Versorgungsnetzwerk

provision <- subgraph.edges(raf, E(raf)[relationship== " 6"]) 
provision <- simplify(provision, remove.multiple = TRUE)
provision

plot(provision,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(provision), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="pink",
     main="Versorgungs-Netzwerk")


#Aktionsbeteiligungs-Netzwerk

participation <- subgraph.edges(raf, E(raf)[relationship== " 7"]) 
participation <- simplify(participation, remove.multiple = TRUE)
participation

#V(participation)[V(raf)$type == 1]$shape <- "circle" # Personen als Kreise
#V(participation)[V(raf)$type == 2]$shape <- "square" # Aktionen als Quadrate
#Hier müssen eigentlich Aktionen und Personen unterschieden werden, aber es funktioniert warum auch immer nicht

plot(participation,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(participation), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="chartreuse",
     main="Aktionsbeteiligungs-Netzwerk")

#Ausbildungsnetzwerk

training <- subgraph.edges(raf, E(raf)[relationship== " 8"]) 
training <- simplify(training, remove.multiple = TRUE)
training

plot(training,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(training), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="cyan",
     main="Ausbildungs-Netzwerk")

#Anwerbungsnetzwerk

recruitment <- subgraph.edges(raf, E(raf)[relationship== " 9"]) 
recruitment <- simplify(recruitment, remove.multiple = TRUE)
recruitment

plot(recruitment,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(recruitment), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="darkslateblue",
     main="Anwerber-Netzwerk")

#Verwandtschafts-Netzwerk:

kinship <- subgraph.edges(raf, E(raf)[relationship== "10"]) 
kinship <- simplify(kinship, remove.multiple = TRUE)
kinship

plot(kinship,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(kinship), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = .7, #gibt die SChriftartgröße an
     edge.color="springgreen",
     main="Verwandtschafts-Netzwerk")




```

