
```{r Ego-Netzwerk von Andreas Baader, ersten Grades}
library(igraph)

# Wir lesen das Netzwerk im Folgenden ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# Uns interessieren die Ego-Netzwerke der Hauptakteure der RAF
# Hierzu sehen wir uns zunächst die degree Werte der Nodes an:
degree(raf)

# daraus ergibt sich folgende Lister der Knoten mit den meisten Verbindungen:
# 1. Andreas Baader (133); 2. Gudrun Ensslin (124); 3. Ulrike Meinhof (74); Jan Carl Raspe (53), Brigitte Mohnhaupt (51), Klaus Croissant (45), Volker Speitel (45), Peter-Jürgen Boock (34)

# ego_size() zeigt uns den Wert mit den höchsten Verbindungen (degrees)
ego_size(raf)
V(raf)$egos <- ego_size(raf)
vertex.attributes(raf)$egos

which.max(vertex.attributes(raf)$egos)

# Baader hat die meisten Knoten, wie der obige Befehl nochmals bestätigt. Daher soll im folgenden sein Egonetzwerk erstellt werden.

# erzeugt ein Egonetzwerk
ego_ab <- make_ego_graph(raf, order = 1, nodes = V(raf)$name == "Andreas Baader", mode ="all")
ego_ab
ego_ab1 <- ego_ab[[1]]

ego_ab1 <- simplify(ego_ab1, remove.multiple = TRUE)

list.vertex.attributes(ego_ab1)

ego_ab1

#Nun wird die Visualisierung des Netzwerkes angepasst
V(ego_ab1)[V(ego_ab1)$type == 1]$shape <- "circle" # Personen werden als Quadrat dargestellt
V(ego_ab1)[V(ego_ab1)$type == 1]$color <- "blue" # Personen werden blau dargestellt
V(ego_ab1)[V(ego_ab1)$name == "Andreas Baader"]$color <- "red" # Baader wird rot hervorgehoben
V(ego_ab1)[V(ego_ab1)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_ab1)[V(ego_ab1)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

ego_ab1

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_ab1) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

#par(mfrow=c(2,2), mar=c(3,3,3,3)) #Austesten verschiedener Layout-Optionen
#plot(raf_eins, rescale=F, layout=l*0.4)
#plot(raf_eins, rescale=F, layout=l*0.8)
#plot(raf_eins, rescale=F, layout=l*1.2)
#plot(raf_eins, rescale=F, layout=l*1.6)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Netzwerk der Mitglieder der 1. Generation geplottet:
plot(ego_ab1,
     main="Ego-Netzwerk von Andreas Baader",
     sub="Beziehungen ersten Grades; Kreis = Person, Aktion = Quadrat, roter Kreis = Andreas Baader",
     rescale=TRUE, 
     layout=l*1.76,
     vertex.size=5,
     asp=0) #der ganze Platz wird ausgenutzt

```

```{r Ego-Netzwerk Baader Beziehungen 1. Grades (nur Personen)}

ego_ab1 <- ego_ab[[1]]
ego_ab1
#Grafisch werden Ereignisse/Aktionen  anders dargestellt als Akteure
V(ego_ab1)[V(ego_ab1)$type == 1]$shape <- "circle" # Personen als Kreise
V(ego_ab1)[V(ego_ab1)$type == 2]$shape <- "square" # Aktionen als Quadrate
V(ego_ab1)[V(ego_ab1)$type == 1]$color <- "blue" #Personen blau einfärben
V(ego_ab1)[V(ego_ab1)$sex == 1]$color <- "pink" # Männer rosa einfärben
V(ego_ab1)[V(ego_ab1)$sex == 2]$color <- "lightblue" #Frauen blau einfärben
V(ego_ab1)[V(ego_ab1)$type == 2]$color <- "orange" #Aktionen orange einfärben
V(ego_ab1)[V(ego_ab1)$name == "Andreas Baader"]$color <- "red" #Baader rot hervorheben

ego_ab1 <- simplify(ego_ab1, remove.multiple = TRUE)
ego_ab1 <- delete_vertices(ego_ab1, V(ego_ab1)[type != "1"]) #es werden alle Knoten gelöscht, die zu Baader eine Verbindung haben und KEINE natürlichen Personen sind

# Nun werden verschiedene Visualisierungsoptionen ausprobiert, um eine möglichst entzerrte Darstellung zu erreichen
l <- layout_with_kk(ego_ab1)

l <- norm_coords(l, ymin=-1, ymax=1, xmin=-4, xmax=4)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Egonetzwerk von Baader geplottet
plot(ego_ab1,  
     edge.curved=curve_multiple(ego_ab1),  
     vertex.size=5,
     vertex.label.color="black",
     vertex.label.size=3,
     rescale=T, 
     layout=l*1.5, 
     asp=0,
     main="Ego-Netzwerk Andreas Baader, direkte Beziehungen (natürl. Pers.)",
     sub="rot = Andreas Baader, rosa = Männer, blau = Frauen")

```

```{r Ego-Netzwerk Andreas Baader; Beziehungen 2. Grades}

ego_ab

ego_ab2 <- make_ego_graph(raf, order = 2, nodes = V(raf)$name == "Andreas Baader", mode ="all")
ego_ab2 <- ego_ab2[[1]]


ego_ab2 <- simplify(ego_ab2, remove.multiple = TRUE) # doppelte Edges werden entfernt, damit zwischen zwei Knoten mit Beziehungen nicht unzählige Verbindungen dargestellt werden. Das wäre zu unübersichtlich und eine Verbindung reicht aus, um in diesem Schritt zu zeigen, dass zwei Akteure etwas miteinander zu tun hatten

list.vertex.attributes(ego_ab2)

ego_ab2

# Veränderung der Farben der Knoten zu deren besseren Unterscheidung
V(ego_ab2)[V(ego_ab2)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_ab2)[V(ego_ab2)$type == 1]$color <- "blue" # Personen werden blau dargestellt
V(ego_ab2)[V(ego_ab2)$name == "Andreas Baader"]$color <- "red" # Baader wird rot hervorgehoben
V(ego_ab2)[V(ego_ab2)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_ab2)[V(ego_ab2)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

ego_ab2

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_ab2) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

#par(mfrow=c(2,2), mar=c(3,3,3,3)) #Austesten verschiedener Layout-Optionen
#plot(raf_eins, rescale=F, layout=l*0.4)
#plot(raf_eins, rescale=F, layout=l*0.8)
#plot(raf_eins, rescale=F, layout=l*1.2)
#plot(raf_eins, rescale=F, layout=l*1.6)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Ego-Netzwerk von Baader geplottet:
plot(ego_ab2,
     layout=layout_with_kk,
     main="Ego-Netzwerk von Andreas Baader",
     sub="Beziehungen zweiten Grades; Kreis = Person, Aktion = Quadrat, roter Kreis = Andreas Baader",
     rescale=TRUE, 
     layout=l*1.7,
     vertex.size=5, # setzt die Knotengröße auf 5
     asp=0) # der ganze Raum wird ausgenutzt
```

```{r Ego-Netzwerk Baader - Beziehungen dritten Grades}
# nun wollen wir noch die Beziehungen dritten Grades miteinbeziehen

ego_ab

ego_ab3 <- make_ego_graph(raf, order = 3, nodes = V(raf)$name == "Andreas Baader", mode ="all")
ego_ab3 <- ego_ab3[[1]]

ego_ab3 <- simplify(ego_ab3, remove.multiple = TRUE) # doppelte Edges werden entfernt, damit zwischen zwei Knoten mit Beziehungen nicht unzählige Verbindungen dargestellt werden. Das wäre zu unübersichtlich und eine Verbindung reicht aus, um in diesem Schritt zu zeigen, dass zwei Akteure etwas miteinander zu tun hatten

ego_ab3

# Veränderung der Farben / Formen  der Knoten zu deren besseren Unterscheidung
V(ego_ab3)[V(ego_ab3)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_ab3)[V(ego_ab3)$type == 1]$color <- "blue" # Personen werden blau dargestellt
V(ego_ab3)[V(ego_ab3)$name == "Andreas Baader"]$color <- "red" # Baader wird rot hervorgehoben
V(ego_ab3)[V(ego_ab3)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_ab3)[V(ego_ab3)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

ego_ab3
# Nun wird das Ego-Netzwerk von Baader geplottet:
plot(ego_ab3,
     layout=layout_with_kk,
     main="Ego-Netzwerk von Andreas Baader, Beziehungen dritten Grades",
     sub="Kreis = Person, Aktion = Quadrat, roter Kreis = Andreas Baader",
     rescale=TRUE, 
     layout=l*1.6,
     vertex.size=5,
     asp=0)

```


``` {r Ego-Netzwerk von Gudrun Ensslin}

library(igraph)

# Wir lesen das Netzwerk im Folgenden neu ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# Uns interessieren die Ego-Netzwerke der Hauptakteure der RAF
# nach Baader hat Ensslin die zweithöchste Zahl an Verbindungen
# Daher soll nun auch ihr Egonetzwerk visualisiert werden

# erzeugt ein Egonetzwerk
ego_ge <- make_ego_graph(raf, order = 1, nodes = V(raf)$name == "Gudrun Ensslin", mode ="all")
ego_ge
ego_ge1 <- ego_ge[[1]]

ego_ge1 <- simplify(ego_ge1, remove.multiple = TRUE)

ego_ge1

#Zur besseren Unterscheidung werden die Knoten verschieden eingefärbt und ihnen verschiedene Formen zugewiesen
V(ego_ge1)[V(ego_ge1)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_ge1)[V(ego_ge1)$sex == 1]$color <- "pink" # Männer werden pink dargestellt
V(ego_ge1)[V(ego_ge1)$sex == 2]$color <- "blue" # Frauen werden pink dargestellt
V(ego_ge1)[V(ego_ge1)$name == "Gudrun Ensslin"]$color <- "red" # Ensslin wird rot hervorgehoben
V(ego_ge1)[V(ego_ge1)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_ge1)[V(ego_ge1)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

ego_ge1

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_ge1) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Netzwerk der Mitglieder der 1. Generation geplottet:
plot(ego_ge1,
     main="Ego-Netzwerk von Gudrun Ensslin",
     sub="Beziehungen ersten Grades; Kreis = Person, Aktion = Quadrat, roter Kreis = Gudrun Ensslin",
     rescale=TRUE, 
     layout=l*1.2,
     vertex.size=5,
     asp=0)

# nun selektieren wir nur Personen, sodass nur angezeigt wird, mit welchen Personen und nicht mit welchen Aktionen Ensslin direkt verbunden war

ego_ge1_p <- make_ego_graph(ego_ge1, order = 1, nodes = V(ego_ge1)$name == "Gudrun Ensslin", mode ="all")

ego_ge1_p <- delete_vertices(ego_ge1, V(ego_ge1)[type != "1"]) # löscht alle Knoten, die keine natürlichen Personen sind (im Codebuch ist dafür das Attribut type definiert, das die Werte 1 = natürliche Person und 2 = Aktion besitzt)

plot(ego_ge1_p,
     main="Ego-Netzwerk von Gudrun Ensslin",
     sub="Beziehungen ersten Grades; Kreis = Person, roter Kreis = Gudrun Ensslin",
     rescale=T, 
     layout=l*1.76,
     vertex.size=5,
     asp=0)

# warum taucht Ensslin zweimal auf??? das muss ich noch mal anschauen :/, weil beim ersten Egonetzwerk mit Akteuren und Personen passt es noch

```

```{r Ego-Netzwerk Ulrike Meinhof}
raf

# Uns interessieren die Ego-Netzwerke der Hauptakteure der RAF
# Ulrike Meinhof hat die drittmeisten Verbindungen, etwa 73 
# Daher soll nun auch ihr Egonetzwerk visualisiert werden

# erzeugt ein Egonetzwerk
ego_um <- make_ego_graph(raf, order = 1, nodes = V(raf)$name == "Ulrike Meinhof", mode ="all")
ego_um
ego_um1 <- ego_um[[1]]

ego_um1 <- simplify(ego_um1, remove.multiple = TRUE) # entfernt alle doppelten / mehrfachen Beziehungen zwischen zwei Knoten, da es ausreicht, eine Verbindung zu sehen, um zu wissen, dass die Akteure etwas miteinander zu tun hatten

ego_um1

# Anpassung der Darstellung der Knoten: verschiedene Formen und Farben zur besseren Unterscheidbarkeit
V(ego_um1)[V(ego_um1)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_um1)[V(ego_um1)$sex == 1]$color <- "pink" # Männer werden pink dargestellt
V(ego_um1)[V(ego_um1)$sex == 2]$color <- "blue" # Frauen werden pink dargestellt
V(ego_um1)[V(ego_um1)$name == "Ulrike Meinhof"]$color <- "red" # Meinhof wird rot hervorgehoben
V(ego_um1)[V(ego_um1)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_um1)[V(ego_um1)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

ego_um1

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_um1) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Ego-Netzwerk von Meinhof geplottet:
plot(ego_um1,
     main="Ego-Netzwerk von Ulrike Meinhof",
     sub="Beziehungen ersten Grades; Kreis = Person, Aktion = Quadrat, roter Kreis = Ulrike Meinhof",
     rescale=TRUE, 
     layout=l*1.76,
     vertex.size=5,
     asp=0) #legt fest, dass der ganze Raum ausgefüllt werden soll
```

```{r Ego-Netzwerk Jan-Carl Raspe}
raf

# Uns interessieren die Ego-Netzwerke der Hauptakteure der RAF
# Raspe hat zwar nur um die 45 Verbindungen, war aber zentraler Akteur in der ersten Generation 
# Daher soll nun auch sein Egonetzwerk visualisiert werden

# erzeugt ein Egonetzwerk
ego_jcr <- make_ego_graph(raf, order = 1, nodes = V(raf)$name == "Jan-Carl Raspe", mode ="all")
ego_jcr
ego_jcr1 <- ego_jcr[[1]]

ego_jcr1 <- simplify(ego_jcr1, remove.multiple = TRUE)# entfernt alle doppelten / mehrfachen Beziehungen zwischen zwei Knoten, da es ausreicht, eine Verbindung zu sehen, um zu wissen, dass die Akteure etwas miteinander zu tun hatten

ego_jcr1

# Anpassung der Darstellung der Knoten: verschiedene Formen und Farben zur besseren Unterscheidbarkeit

V(ego_jcr1)[V(ego_jcr1)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_jcr1)[V(ego_jcr1)$sex == 1]$color <- "pink" # Männer werden pink dargestellt
V(ego_jcr1)[V(ego_jcr1)$sex == 2]$color <- "lightblue" # Frauen werden blau dargestellt
V(ego_jcr1)[V(ego_jcr1)$name == "Jan-Carl Raspe"]$color <- "red" # Meinhof wird rot hervorgehoben
V(ego_jcr1)[V(ego_jcr1)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_jcr1)[V(ego_jcr1)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

ego_jcr1

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_um1) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Ego-Netzwerk von Raspe geplottet:
plot(ego_jcr1,
     layout=layout_with_kk,
     main="Ego-Netzwerk von Jan-Carl Raspe",
     sub="Beziehungen ersten Grades; Kreis = Person, Aktion = Quadrat, roter Kreis = J-C Raspe",
     rescale=TRUE, 
     layout=l*1.76,
     vertex.size=5,
     asp=1)

# nun selektieren wir nur Personen, sodass nur angezeigt wird, mit welchen Personen und nicht mit welchen Aktionen Raspe direkt verbunden war
ego_jcr1_p <- delete_vertices(ego_jcr1, V(ego_jcr1)[type > "1"]) # löscht alle Knoten, die keine natürlichen Personen sind (im Codebuch ist dafür das Attribut type definiert, das die Werte 1 = natürliche Person und 2 = Aktion besitzt)

plot(ego_jcr1_p,
     main="Ego-Netzwerk von Raspe",
     sub="Beziehungen ersten Grades; Kreis = Person, roter Kreis = Raspe",
     rescale=TRUE, 
     layout=l*1.76,
     vertex.size=5,
     asp=1)
```

```{r Ego-Netzwerk Peter-Jürgen Boock}

raf

# selektiert aus dem Netzwerk raf_personen alle Knoten, die mit Boock über einen Schritt verbunden sind.
ego_pb <- make_ego_graph(raf, order=1, nodes = V(raf)$name == "Peter-Juergen Boock", mode = "all")
# liefert eine Liste der Verbindungen (in diesem Falle alle out/indgree Beziehungen von Boock)
ego_pb
#man braucht diesen Zwischenschrit, damit das igraph-Objekt hergestellt wird
ego_pb1 <- ego_pb[[1]]
ego_pb1 <- simplify(ego_pb1, remove.multiple = TRUE)# entfernt alle doppelten / mehrfachen Beziehungen zwischen zwei Knoten, da es ausreicht, eine Verbindung zu sehen, um zu wissen, dass die Akteure etwas miteinander zu tun hatten

ego_pb1

# Anpassung der Darstellung der Knoten: verschiedene Formen und Farben zur besseren Unterscheidbarkeit
V(ego_pb1)[V(ego_pb1)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_pb1)[V(ego_pb1)$sex == 1]$color <- "pink" # Männer werden pink dargestellt
V(ego_pb1)[V(ego_pb1)$sex == 2]$color <- "lightblue" # Frauen werden pink dargestellt
V(ego_pb1)[V(ego_pb1)$name == "Peter-Juergen Boock"]$color <- "red" # Boock wird rot hervorgehoben
V(ego_pb1)[V(ego_pb1)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_pb1)[V(ego_pb1)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_pb1) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-5, xmax=5)

plot(ego_pb1, 
     layout=layout_with_kk,
     rescale=T,
     layout=l*1.4,
     asp=0,
     main="Ego-Netzwerk Peter-Jürgen Boock, erster Grad",
     sub="nur direkte Beziehungen des ersten Grads",
     edge.color="grey70",
     vertex.label.size=2,
     vertex.size=5)

# nun selektieren wir nur Personen, sodass nur angezeigt wird, mit welchen Personen und nicht mit welchen Aktionen Boock direkt verbunden war
ego_pb1_p <- delete_vertices(ego_pb1, V(ego_pb1)[type > "1"]) # löscht alle Knoten, die keine natürlichen Personen sind (im Codebuch ist dafür das Attribut type definiert, das die Werte 1 = natürliche Person und 2 = Aktion besitzt)

ego_pb1_p

# da Boock als Broker gesehen werden könnte, soll nun hervorgehoben werden, welcher Generation seine direkten Verbindungen angehörten
V(ego_pb1)[V(ego_pb1)$generation == 1]$color <- "blue"
V(ego_pb1)[V(ego_pb1)$generation == 2]$color <- "green"

plot(ego_pb1_p,
     layout=layout_with_kk,
     main="Ego-Netzwerk von Boock",
     sub="Beziehungen ersten Grades; Kreis = Person, roter Kreis = Boock",
     rescale=TRUE, 
     layout=l*1.76,
     vertex.size=5,
     asp=0) #legt fest, dass der ganze Raum ausgenutzt werden soll
```

``` {r Ego-Netzwerk von Volker Speitel; Bzgh. ersten Grades}

library(igraph)

# Wir lesen das Netzwerk im Folgenden neu ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# Uns interessieren die Ego-Netzwerke der Hauptakteure der RAF
# Volker Speitel hat zwar "nur" 45 Verbindungen, verglichen mit einen zentralen Akteur wie Raspe (54 Verbindungen), sind das aber doch überraschend viele
# Daher soll nun auch sein Egonetzwerk visualisiert werden

# erzeugt ein Egonetzwerk
ego_vs <- make_ego_graph(raf, order = 1, nodes = V(raf)$name == "Volker Speitel", mode ="all")
ego_vs
ego_vs1 <- ego_vs[[1]]

ego_vs1 <- simplify(ego_vs1, remove.multiple = TRUE)# entfernt alle doppelten / mehrfachen Beziehungen zwischen zwei Knoten, da es ausreicht, eine Verbindung zu sehen, um zu wissen, dass die Akteure etwas miteinander zu tun hatten

ego_vs1

# Anpassung der Darstellung der Knoten: verschiedene Formen und Farben zur besseren Unterscheidbarkeit
V(ego_vs1)[V(ego_vs1)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_vs1)[V(ego_vs1)$sex == 1]$color <- "pink" # Männer werden pink dargestellt
V(ego_vs1)[V(ego_vs1)$sex == 2]$color <- "lightblue" # Frauen werden pink dargestellt
V(ego_vs1)[V(ego_vs1)$name == "Volker Speitel"]$color <- "red" # Volker Speitel wird rot dargestellt
V(ego_vs1)[V(ego_vs1)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

ego_vs1

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_vs1) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Egonetzwerk von Speitel geplottet:
plot(ego_vs1,
     main="Ego-Netzwerk von Volker Speitel",
     sub="Beziehungen ersten Grades; Kreis = Person, Aktion = Quadrat, roter Kreis = Volker Speitel",
     rescale=TRUE, 
     layout=l*1.76,
     vertex.size=5,
     asp=0) #legt fest, dass der ganze Raum ausgenutzt weden soll

```

```{r Ego-Netzwerk Brigitte Mohnhaupt}
# selektiert aus dem Netzwerk raf alle Knoten, die mit Mohnhaupt über einen Schritt verbunden sind.
raf
ego_bm <- make_ego_graph(raf, order=1, nodes = V(raf)$name == "Brigitte Mohnhaupt", mode = "all")
# liefert eine Liste der Verbindungen 
ego_bm
#man braucht diesen Zwischenschrit, damit das igraph-Objekt hergestellt wird
ego_bm1 <- ego_bm[[1]]
ego_bm1

# selektiert aus dem Netzwerk raf_personen alle Knoten, die mit Boock über einen Schritt verbunden sind.
ego_bm1 <- make_ego_graph(raf, order=1, nodes = V(raf)$name == "Brigitte Mohnhaupt", mode = "all")
# liefert eine Liste der Verbindungen (in diesem Falle alle out/indgree Beziehungen von Mohnhaupt)
ego_bm1
#man braucht diesen Zwischenschrit, damit das igraph-Objekt hergestellt wird
ego_bm1 <- ego_bm[[1]]
ego_bm1 <- simplify(ego_bm1, remove.multiple = TRUE)# entfernt alle doppelten / mehrfachen Beziehungen zwischen zwei Knoten, da es ausreicht, eine Verbindung zu sehen, um zu wissen, dass die Akteure etwas miteinander zu tun hatten

ego_bm1

# Anpassung der Darstellung der Knoten: verschiedene Formen und Farben zur besseren Unterscheidbarkeit
V(ego_bm1)[V(ego_bm1)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_bm1)[V(ego_bm1)$sex == 1]$color <- "pink" # Männer werden pink dargestellt
V(ego_bm1)[V(ego_bm1)$sex == 2]$color <- "lightblue" # Frauen werden hellbau dargestellt
V(ego_bm1)[V(ego_bm1)$name == "Brigitte Mohnhaupt"]$color <- "red" # Mohnhaupt wird rot hervorgehoben
V(ego_bm1)[V(ego_bm1)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_bm1)[V(ego_bm1)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_bm1) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-5, xmax=5)

plot(ego_bm1, 
     layout=layout_with_kk,
     rescale=T,
     layout=l*1.4,
     asp=0,
     main="Ego-Netzwerk Brigitte Mohnhaupt, erster Grad",
     sub="nur direkte Beziehungen des ersten Grads; rosa = Männer; blau = Frauen",
     edge.color="grey80",
     vertex.label.size=2,
     vertex.size=5)

# nun selektieren wir nur Personen, sodass nur angezeigt wird, mit welchen Personen und nicht mit welchen Aktionen Mohnhaupt direkt verbunden war
ego_bm1_p <- delete_vertices(ego_bm1, V(ego_bm1)[type > "1"]) # löscht alle Knoten, die keine natürlichen Personen sind (im Codebuch ist dafür das Attribut type definiert, das die Werte 1 = natürliche Person und 2 = Aktion besitzt)

ego_bm1_p

# da Mohnhaupt als Broker gesehen werden könnte, soll nun hervorgehoben werden, welcher Generation ihre direkten Verbindungen angehörten
V(ego_bm1_p)[V(ego_bm1_p)$generation == 1]$color <- "blue"
V(ego_bm1_p)[V(ego_bm1_p)$generation == 2]$color <- "green"

plot(ego_bm1_p,
     layout=layout_with_kk,
     vertex.label.color= "black",
     main="Ego-Netzwerk von Mohnhaupt, Bzgh. 1. Grades",
     sub="blau = 1. Gen.; grün = 2. Gen; rosa = beide / keine Gen., rot = Mohnhaupt",
     rescale=TRUE, 
     layout=l*1.76,
     asp=0)
```

```{r Ego-Netzwerk Klaus Croissant}
raf
ego_kc<- make_ego_graph(raf, order=1, nodes = V(raf)$name == "Klaus Croissant", mode = "all")
# liefert eine Liste der Verbindungen 
ego_kc
#man braucht diesen Zwischenschrit, damit das igraph-Objekt hergestellt wird
ego_kc1 <- ego_kc[[1]]
ego_kc1

# selektiert aus dem Netzwerk raf_personen alle Knoten, die mit Boock über einen Schritt verbunden sind.
ego_kc1 <- make_ego_graph(raf, order=1, nodes = V(raf)$name == "Klaus Croissant", mode = "all")
# liefert eine Liste der Verbindungen (in diesem Falle alle out/indgree Beziehungen von Croissant)
ego_kc1
#man braucht diesen Zwischenschrit, damit das igraph-Objekt hergestellt wird
ego_kc1 <- ego_kc[[1]]
ego_kc1 <- simplify(ego_kc1, remove.multiple = TRUE)# entfernt alle doppelten / mehrfachen Beziehungen zwischen zwei Knoten, da es ausreicht, eine Verbindung zu sehen, um zu wissen, dass die Akteure etwas miteinander zu tun hatten

ego_kc1

# Anpassung der Darstellung der Knoten: verschiedene Formen und Farben zur besseren Unterscheidbarkeit
V(ego_kc1)[V(ego_kc1)$type == 1]$shape <- "circle" # Personen werden als Kreis dargestellt
V(ego_kc1)[V(ego_kc1)$sex == 1]$color <- "pink" # Männer werden pink dargestellt
V(ego_kc1)[V(ego_kc1)$sex == 2]$color <- "lightblue" # Frauen werden hellbau dargestellt
V(ego_kc1)[V(ego_kc1)$name == "Klaus Croissant"]$color <- "red" # Croissant wird rot hervorgehoben
V(ego_kc1)[V(ego_kc1)$type == 2]$color <- "orange" # Anschläge werden orange dargestellt
V(ego_kc1)[V(ego_kc1)$type == 2]$shape <- "square" # Anschläge werden als Quadrat dargestellt

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(ego_kc1) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-5, xmax=5)

plot(ego_kc1, 
     layout=layout_with_kk,
     rescale=T,
     layout=l*1.4,
     asp=0,
     main="Ego-Netzwerk Klaus Croissant, erster Grad",
     sub="nur direkte Beziehungen des ersten Grads; rosa = Männer; blau = Frauen",
     edge.color="grey80",
     vertex.label.size=2,
     vertex.size=5)

# nun selektieren wir nur Personen, sodass nur angezeigt wird, mit welchen Personen und nicht mit welchen Aktionen Croissant direkt verbunden war
ego_kc1_p <- delete_vertices(ego_kc1, V(ego_kc1)[type > "1"]) # löscht alle Knoten, die keine natürlichen Personen sind (im Codebuch ist dafür das Attribut type definiert, das die Werte 1 = natürliche Person und 2 = Aktion besitzt)

ego_kc1_p

# da Croissant als Anwalt viele seiner Angestellten zur RAF gebracht und gewissermaßen als Broker gesehen werden könnte, soll nun hervorgehoben werden, welcher Generation seine direkten Verbindungen angehörten, um herauszufinden, ob er auch als Verbindung zwischen den Generationen fungierte
V(ego_kc1_p)[V(ego_kc1_p)$generation == 1]$color <- "blue"
V(ego_kc1_p)[V(ego_kc1_p)$generation == 2]$color <- "green"

par(mar=c(0,0,0,0)) #setzt die Ränder auf 0

plot(ego_kc1_p,
     layout=layout_with_kk,
     vertex.label.color= "black",
     main="Ego-Netzwerk von Croissant. Bzgh. 1. Grades",
     sub=" blau = 1. Gen.; grün = 2. Gen.; rosa = beide / keine Gen.; rot = Croissant",
     asp=0, #definiert, dass der gesamte Raum ausgenutzt werden soll
     rescale=TRUE, 
     layout=l*1.76)
```

