---
title: "RAF Gesamtnetzwerk"
author: "Hannah Bauer"
date: "9 3 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Skript Erstellung einfaches Netzwerk
# lädt igraph Bibliothek (ggf. vorher installieren)
library(igraph)
# erhöht das limit auf 10000000
options(max.print=1000000)
# liest die Edgelist als "el" ein
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
# liest die Nodelist mit den Namen ein
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")
# Zwischenschritt verbindet die Edge- und Nodelist zu einer Matrix
raf_matrix <- as.matrix(el)
# zeigt die Matrix an
raf_matrix
# generiert ein igraph-Objekt (dataframe) aus der Matrix, das ungerichtet ist (directed = false)
raf <- graph_from_data_frame(d=raf_matrix, vertices=nodes, directed=FALSE)
# ruft unser neues igraph-Objekt auf
raf
# generiert die Standard-Visualisierung des Netzwerks
#plot(raf)
#degree <- degree(raf)
#degree
#test, ob Anfangsproblem behoben ist (d.h. alle Nodeattribute eingelesen werden und in die Matrix übernommen wurden)
#list.vertex.attributes(raf)
#Grafisch werden Ereignisse/Aktionen  anders dargestellt als Akteure
V(raf)[V(raf)$type == 1]$shape <- "circle" # Personen als Kreise
V(raf)[V(raf)$type == 2]$shape <- "square" # Aktionen als Quadrate
# einfacher plot
plot(raf,
     layout=layout_nicely,
     main="RAF-Netzwerk")
```
```{r diameter, exercise=TRUE, exercise.lines = 15}
## 2 Berechnung des Durchmessers und der Pfaddistanz
#Diameter beschreibt den längsten Pfad innerhalb eines Netzwerks, also die maximal mögliche Distanz zwischen zwei Knoten innerhalb des Netzwerks. 

#Pfadistanz ist ein Maß für die Anzahl der Schritte, dies es braucht, um ein Netzwerk zu "durchschreiten". Dabei sind die kürzesten und längsten Pfaddistanzen wichtige Aussagen.

# Was ist die maximale Distanz zwischen zwei Knoten im Netzwerk?
# Achtung: bei Netzwerken mit Kantengewicht müssen die Kantengewichte ausgeschaltet werden! 
diameter(raf, weights = NA)

# Welche Knoten sind am weitesten voneinander entfernt, also haben die längsten Schritte??
farthest_vertices(raf) 
```