ERSTELLUNG TEILNETZWERK "ANSCHLÄGE"

#Selektion Teilnetzwerk Anschläge

```{r Teilnetzwerke nach Vertex-Attributen (delete_vertices)}
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=T)
raf

# Zeigt uns die Vertex-Attribute des Unternetzwerks "Anschläge" an.
vertex_attr(raf)

# Wir wollen nun wissen, wie das Teilnetzwerk "Anschläge" aussieht:
raf_anschlaege <- delete_vertices(raf, V(raf)[type < "2"]) # löscht Personen
raf_anschlaege
plot(raf_anschlaege, layout=layout_with_kk,
     main="Anschläge",
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.color="red",
     sub="n=29, 110 Kanten")
```
##Selektion Anschläge nur 1977
#Teilnetzwerk vom Teilnetzwerk "Anschläge"
```{r delete_vertices, exercise=TRUE, exercise.lines = 15}

#Anzeigen Vertex-Attribute des obigen Netzwerks "Anschläge)
vertex_attr(raf_anschlaege)

raf_anschlaege_1977 <- delete_vertices(raf_anschlaege, V(raf_anschlaege)[year > "1977"])
raf_anschlaege_1977 <- delete_vertices(raf_anschlaege, V(raf_anschlaege)[year < "1977"])
raf_anschlaege_1977
plot(raf_anschlaege_1977, layout=layout_with_kk,
     main="Anschläge 1977",
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.color="pink",
     sub="n=29, 110 Kanten")
```
#beim ersten Mal hat es geklappt aber jetzt zeigt das dumme Ding aus irgendeinem Grund auch die Jahreszahlen > 1977 an, obwohl Löschbefehl angegeben
#why