---
title: "Gesamtzusammenstellung"
author: "ja053"
date: "1 6 2020"
output: html_document
---

# Set-Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Wichtigste Packages abrufen}

#Vorab werden die wichtigsten Packages geladen

library(igraph)
library(igraphdata)
library(knitr) 
library(rmarkdown)
```
# Gesamtnetzwerk
```{r Gesamtnetzwerk einlesen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

# Zunächst soll das Gesamtnetzwerk der RAF generiert werden.

# Dazu werden zuerst Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")

nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# Nun wird die Visualisierung der Knoten und Kanten angepasst.

#Graphisch werden Ereignisse/Aktionen anders dargestellt als Akteure. Zudem wird bei den Akteuren optisch zwischen 1. und 2. Generation unterschieden

V(raf)[V(raf)$type == 1]$shape <- "circle" # Personen werden als Kreise dargestellt
V(raf)[V(raf)$type == 2]$shape <- "square" # Aktionen werden als Quadrate dargestellt
V(raf)[V(raf)$generation == 1]$color <- "grey80" # Knoten der Mitglieder der 1. Generation werden in Farbe grey80 dargestellt
V(raf)[V(raf)$generation == 2]$color <- "grey30" # Knoten der Mitglieder der 2. Generation werden in Farbe grey30 dargestellt
V(raf)[V(raf)$generation == 3]$color <- "white" # Knoten der Mitglieder beider Generation werden weiß eingefärbt
V(raf)[V(raf)$generation == 4]$color <- "lightpink" # Knoten der Unterstützer*innen werden hellrosa eingefärbt
V(raf)[V(raf)$generation == 99]$color <- "white" # Knoten, zu denen keine Angabe bzgl. iher Generation vorliegt, werden weiß eingefärbt
V(raf)[V(raf)$generation == 3]$vertex.frame <- "black" # weiß gefärbte Knoten sollen zur besseren Sichtbarkeit einen schwarzen Rahmen erhalten
V(raf)[V(raf)$generation == 99]$vertex.frame <- "black" # weiß gefärbte Knoten sollen zur besseren Sichtbarkeit einen schwarzen Rahmen erhalten
V(raf)[V(raf)$type == 2]$color <- "cornflowerblue" # Knoten der Aktionen werden kornblumenblau gefärbt

# definiert die Farbe aller Kanten
E(raf)$color <- "grey40"

raf <- simplify(raf, remove.multiple = TRUE) # es werden keine doppelten oder mehrfachen Beziehungen angezeigt

# Visualisierung des Netzwerks
plot(raf,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     edge.curved=curve_multiple(raf), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="Gesamtnetzwerk der RAF",
     sub="erste und zweite Generation, hellgrau = 1. Generation, dunkelgrau = 2. Generation, \n weiß = beide Generationen / keine Angabe, hellrosa = Unterstützer*innen, blau = Aktionen")

# Da es einige Knoten im Gesamtnetzwerk gibt, die nur als Unterstützer*innen tätig waren, soll nun ein Netzwerk erstellt werden, in dem diese ausgeblendet und nur wirkliche Mitglieder dargestellt werden.

raf_mem <- delete.vertices(raf, V(raf)[generation == "4"]) # löscht alle Unterstützer*innen
raf_mem <- simplify(raf_mem, remove.multiple = TRUE) # es werden keine doppelten oder mehrfachen Beziehungen angezeigt
raf_mem # generiert das igraph-Objekt

# Visualisierung des neuen Netzwerks:
plot(raf_mem,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     edge.curved=curve_multiple(raf_mem), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="Gesamtnetzwerk der RAF (ohne Unterstützer*innen)",
     sub="erste und zweite Generation, hellgrau = 1. Generation, dunkelgrau = 2. Generation, \n weiß = beide Generationen / keine Angabe, blau = Aktionen")

```
#Visualisierung der einzelnen Jahre
```{r 1970,fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE }
# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")
#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)

raf_year <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf_year
#Wir selektieren die Akteure, die 1970 eingetreten sind:
raf_1970 <- delete_vertices(raf_year, V(raf_year) [entry !="1970"])# löscht die Akteure, die nicht 1970 eingetreten sind
#Löschen die Akteure, die vorher ausgetreten oder gestorben sind (macht im ersten Jahr keinen Sinn, deswegen nur kommentiert)
#raf_1970 <- delete_vertices(raf_1970, V(raf_1970) [yearofresignation <= "1969"]) 
#raf_1970 <- delete_vertices(raf_1970, V(raf_1970) [symbolicdeath <="1970"])
raf_1970 <- subgraph.edges(raf_1970, E(raf_1970)[year==1970]) #selektiert die Beziehungen von 1970
raf_1970 <- simplify(raf_1970, remove.multiple=TRUE,) #löscht doppelte Beziehungen
V(raf_1970) [V(raf_1970)$entry == 1970]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
raf_1970
# Nun wird das Netzwerk der Mitglieder von 1970 visualisiert
plot(raf_1970,
     asp=0, #definiert, dass der ganze Raum ausgenutzt werden soll
     layout=layout_with_kk,
     edge.curved=curve_multiple(raf_1970), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = 1, #gibt die SChriftartgröße an
     main="RAF 1970",
     sub="Neue Mitglieder sind rot eingefärbt")
```

```{r 1971, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE }
#Nun kommen die von 1971 dazu:
raf_year
raf_1971 <- delete.vertices(raf_year, V(raf_year) [entry >="1972"])#löscht alle Akteure, die nach 1971 dazugekommen sind
raf_1971 <- delete.vertices(raf_1971, V(raf_1971) [yearofresignation <= "1970"])#löscht die Ausgetretenen des Vorjahres
raf_1971 <- delete.vertices(raf_1971, V(raf_1971) [symbolicdeath <="1970"])#löscht die Gestorbenen des Vorjahres
#raf_1971 <- subgraph.edges(raf_1971, E(raf_1971)[year=1971]) #selektiert die Beziehungen des entsprechenden 
raf_1971 <- simplify(raf_1971, remove.multiple=TRUE,) #löscht doppelte Beziehungen
V(raf_1971) [V(raf_1971)$entry == 1971]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
V(raf_1971) [V(raf_1971)$entry != 1971]$color <- "white"
raf_1971
# Nun wird das Netzwerk der Mitglieder von 1971 visualisiert
plot(raf_1971,
     asp=0, 
     layout=layout_with_kk,
     edge.curved=curve_multiple(raf_1971), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = 1, #gibt die SChriftartgröße an
     main="RAF 1971",
     sub ="Neue Mitglieder sind rot eingefärbt")
```

```{r 1972, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}
#Nun kommen die von 1972 dazu:

raf_year
raf_1972 <- delete.vertices(raf_year, V(raf_year) [entry >="1973"])
raf_1972 <- delete.vertices(raf_1972, V(raf_1972) [yearofresignation <= "1971"])#löscht die Ausgetretenen des Vorjahres
raf_1972 <- delete.vertices(raf_1972, V(raf_1972) [symbolicdeath <="1971"])#löscht die Gestorbenen des Vorjahres

#raf_1972 <- subgraph.edges(raf_1972, E(raf_1972)[year==1972]) #selektiert die Beziehungen von 1972
raf_1972 <- simplify(raf_1972, remove.multiple=TRUE,) #löscht doppelte Beziehungen
V(raf_1972) [V(raf_1972)$entry == 1972]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
V(raf_1972) [V(raf_1972)$entry != 1972]$color <- "white"
raf_1972
# Nun wird das Netzwerk der Mitglieder von 1972 visualisiert
plot(raf_1972,
     asp=0,
     layout=layout_with_kk(raf_1972),
     edge.curved=curve_multiple(raf_1972), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = 1, #gibt die SChriftartgröße an
     main="RAF 1972",
     sub ="Neue Mitglieder sind rot eingefärbt")
```

```{r RAF 1973, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}
#Nun kommen die von 1973 dazu:

raf_year
raf_1973 <- delete_vertices(raf_year, V(raf_year) [entry >="1974"])
raf_1973 <- delete_vertices(raf_1973, V(raf_1973) [yearofresignation <= "1972"])#löscht die Ausgetretenen des Vorjahres
raf_1973 <- delete_vertices(raf_1973, V(raf_1973) [symbolicdeath <="1972"])#löscht die Gestorbenen des Vorjahres
#raf_1973 <- subgraph.edges(raf_1973, E(raf_1973)[year==1973]) #selektiert die Beziehungen von 1970
raf_1973 <- simplify(raf_1973, remove.multiple=TRUE,) #löscht doppelte Beziehungen
V(raf_1973) [V(raf_1973)$entry == 1973]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
V(raf_1973) [V(raf_1973)$entry != 1973]$color <- "white" #Alle übrigen Mitglieder werden weiß eingefärbt

raf_1973
# Nun wird das Netzwerk der Mitglieder von 1973 visualisiert
plot(raf_1973,
     asp=0,
     layout=layout_with_kk(raf_1973),
     edge.curved=curve_multiple(raf_1973), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = 1, #gibt die SChriftartgröße an
     main="RAF 1973",
     sub ="Neue Mitglieder sind rot eingefärbt")
```

```{r RAF 1974, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}
#Nun kommen die von 1974 dazu:
raf_year
raf_1974 <- delete_vertices(raf_year, V(raf_year) [entry >="1975"])
raf_1974 <- delete_vertices(raf_1974, V(raf_1974) [yearofresignation <= "1973"])#löscht die Ausgetretenen des Vorjahres
raf_1974 <- delete_vertices(raf_1974, V(raf_1974) [symbolicdeath <="1973"])#löscht die Gestorbenen des Vorjahres
#raf_1974 <- subgraph.edges(raf_1974, E(raf_1974)[year==1974]) #selektiert die Beziehungen von 1970
raf_1974 <- simplify(raf_1974, remove.multiple=TRUE,) #löscht doppelte Beziehungen
V(raf_1974) [V(raf_1974)$entry == 1974]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
V(raf_1974) [V(raf_1974)$entry != 1974]$color <- "white" #Alle übrigen Mitglieder werden weiß eingefärbt
raf_1974
# Nun wird das Netzwerk der Mitglieder von 1974 visualisiert
plot(raf_1974,
     asp=0,
     layout=layout_with_kk(raf_1974),
     edge.curved=curve_multiple(raf_1974), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung vom Zentrum
     vertex.label.cex = 1, #gibt die SChriftartgröße an
     main="RAF 1974",
     sub ="Neue Mitglieder sind rot eingefärbt")
```

```{r RAF 1975, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}
#Nun kommen die von 1975 dazu:

raf_year
raf_1975 <- delete_vertices(raf_year, V(raf_year) [entry >="1976"])
raf_1975 <- delete_vertices(raf_1975, V(raf_1975) [yearofresignation <= "1974"])#löscht die Ausgetretenen des Vorjahres
raf_1975 <- delete_vertices(raf_1975, V(raf_1975) [symbolicdeath <="1974"])#löscht die Gestorbenen des Vorjahres

#raf_1975 <- subgraph.edges(raf_1975, E(raf_1975)[year==1975]) #selektiert die Beziehungen von 1970

raf_1975 <- simplify(raf_1975, remove.multiple=TRUE,) #löscht doppelte Beziehungen

V(raf_1975) [V(raf_1975)$entry == 1975]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
V(raf_1975) [V(raf_1975)$entry != 1975]$color <- "white" #Alle übrigen Mitglieder werden weiß eingefärbt

raf_1975


# Nun wird das Netzwerk der Mitglieder von 1975 visualisiert

plot(raf_1975,
    asp=0,
    layout=layout_with_kk(raf_1975),
    edge.curved=curve_multiple(raf_1975), # verhindert, dass sich Kanten überlagern
    vertex.size=10,
    vertex.label.color = "black",
    vertex.label.size = .5, # gibt die Größe der Nodes a
    vertex.label.family = "sans", #gibt die Schriftart an
    #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
    #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
    vertex.label.cex = 1, #gibt die SChriftartgröße an
    main="RAF 1975",
    sub ="Neue Mitglieder sind rot eingefärbt")

```

```{r RAF 1976, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}
#Nun kommen die von 1976 dazu:
raf_year
raf_1976 <- delete_vertices(raf_year, V(raf_year) [entry >="1977"])
raf_1976 <- delete_vertices(raf_1976, V(raf_1976) [yearofresignation <= "1975"])#löscht die Ausgetretenen des Vorjahres
raf_1976 <- delete_vertices(raf_1976, V(raf_1976) [symbolicdeath <="1975"])#löscht die Gestorbenen des Vorjahres
#raf_1976 <- subgraph.edges(raf_1976, E(raf_1976)[year==1976]) #selektiert die Beziehungen von 1970
raf_1976 <- simplify(raf_1976, remove.multiple=TRUE,) #löscht doppelte Beziehungen
V(raf_1976) [V(raf_1976)$entry == 1976]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
V(raf_1976) [V(raf_1976)$entry != 1976]$color <- "white" #Alle übrigen Mitglieder werden weiß eingefärbt
raf_1976
# Nun wird das Netzwerk der Mitglieder von 1976 visualisiert
plot(raf_1976,
     asp=0,
     layout=layout_with_kk(raf_1976),
     edge.curved=curve_multiple(raf_1976), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = 1, #gibt die SChriftartgröße an
     main="RAF 1976",
     sub ="Neue Mitglieder sind rot eingefärbt")
```

```{r RAF 1977, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}
#Nun kommen die von 1977 dazu:
raf_year
raf_1977 <- delete_vertices(raf_year, V(raf_year) [entry >="1978"])
raf_1977 <- delete_vertices(raf_1977, V(raf_1977) [yearofresignation <= "1976"])#löscht die Ausgetretenen des Vorjahres
raf_1977 <- delete_vertices(raf_1977, V(raf_1977) [symbolicdeath <="1976"])#löscht die Gestorbenen des Vorjahres
#raf_1977 <- subgraph.edges(raf_1977, E(raf_1977)[year==1977]) #selektiert die Beziehungen von 1970
raf_1977 <- simplify(raf_1977, remove.multiple=TRUE,) #löscht doppelte Beziehungen
V(raf_1977) [V(raf_1977)$entry == 1977]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
V(raf_1977) [V(raf_1977)$entry != 1977]$color <- "white" #Alle übrigen Mitglieder werden weiß eingefärbt
raf_1977
# Nun wird das Netzwerk der Mitglieder von 1977 visualisiert
plot(raf_1977,
     asp=0,
     layout=layout_with_kk(raf_1977),
     edge.curved=curve_multiple(raf_1977), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = 1, #gibt die SChriftartgröße an
     main="RAF Anfang 1977",
     sub ="Neue Mitglieder sind rot eingefärbt")
```


```{r Nach 1977, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}
#Was 1977 noch passiert ist:
raf_year
raf_1977_ende <- delete_vertices(raf_year, V(raf_year) [entry >="1978"])
raf_1977_ende <- delete_vertices(raf_1977_ende, V(raf_1977_ende) [yearofresignation <= "1976"])#löscht die Ausgetretenen des Vorjahres
raf_1977_ende <- delete_vertices(raf_1977_ende, V(raf_1977_ende) [symbolicdeath <="1976"])#löscht die Gestorbenen des Vorjahres
#Die Toten und Ausgetretenen von 1977 werden eingefärbt:
V(raf_1977_ende)[V(raf_1977_ende)$yearofresignation == 1977]$color <-"lightgray" #Ausgetreten
V(raf_1977_ende)[V(raf_1977_ende)$symbolicdeath == 1977]$color <- "black" #Gestorben
#raf_1977_ende <- subgraph.edges(raf_1977, E(raf_1977)[year==1977]) #selektiert die Beziehungen von 1970
raf_1977_ende <- simplify(raf_1977_ende, remove.multiple=TRUE,) #löscht doppelte Beziehungen
V(raf_1977_ende) [V(raf_1977_ende)$entry == 1977]$color <- "red" #Mitglieder, die im angegebenen Jahr hinzukommen, werden rot eingefärbt
#V(raf_1977_ende) [V(raf_1977_ende)$entry != 1977]$color <- "white" #Alle übrigen Mitglieder werden weiß eingefärbt
raf_1977_ende
# Nun wird das Netzwerk der Mitglieder von 1977 visualisiert
plot(raf_1977_ende,
     asp=0,
     layout=layout_with_kk(raf_1977_ende),
     edge.curved=curve_multiple(raf_1977_ende), # verhindert, dass sich Kanten überlagern
     vertex.size=10,
     vertex.label.color = "black",
     vertex.label.size = .5, # gibt die Größe der Nodes a
     vertex.label.family = "sans", #gibt die Schriftart an
     #vertex.label.degree = pi/3, # verschiebt die Beschriftung nach unten
     #vertex.label.dist = 1.2, # verschiebt Beschriftung um 1,2 vom Zentrum
     vertex.label.cex = 1, #gibt die SChriftartgröße an
     main="RAF Ende 1977",
     sub ="Neue Mitglieder sind rot eingefärbt, Ausgetretene grau und Tote schwarz")
```





#Teilnetzwerke
##Betrachten der ersten Generation

```{r 1. Generation mit Anschlägen und Unterstützer*innen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

# Wir schauen uns das Netzwerk der ersten Generation mit Anschlägen und Unterstützer*innen an:

raf

raf_eins <- delete_vertices(raf, V(raf)[generation =="2"]) # löscht alle Knoten, für die der Wert von Generation 2 beträgt, damit bleiben diejenigen, die der ersten und beider Generationen angehört haben. 
V(raf_eins)[V(raf_eins)$generation == "2"]$color <- "grey80" # Knoten der Mitglieder der 1. Generation werden in Farbe grey80 dargestellt
V(raf_eins)[V(raf_eins)$generation == 3]$color <- "white" # Knoten der Mitglieder beider Generation werden weiß eingefärbt
V(raf_eins)[V(raf_eins)$generation == 4]$color <- "lightpink" # Knoten der Unterstützer*innen werden hellrosa eingefärbt
V(raf_eins)[V(raf_eins)$type == 1]$shape <- "circle" # Personen werden als Kreise dargestellt
V(raf_eins)[V(raf_eins)$type == 2]$shape <- "square" # Aktionen werden als Quadrate dargestellt
V(raf_eins)[V(raf_eins)$type == 2]$color <- "cornflowerblue" # Knoten der Aktionen werden kornblumenblau gefärbt


raf_eins

plot(raf_eins,
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     edge.curved=curve_multiple(raf_eins), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="Netzwerk der ersten Generation mit Anschlägen",
     sub="1.Generation = hellgrau / Beide Generationen = weiß / Unterstützer*innen = hellrosa / Anschläge = quadratisch und blau")

```

```{r 1. Generation - nur Personen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

# Nun lassen wir uns nur die Personen der ersten Generation anzeigen - ohne Anschläge

raf_eins

raf_eins_mem <- delete_vertices(raf_eins, V(raf_eins)[type !="1"])# Wir löschen alle Knoten, die als Typ den Wert 1 haben (=Anschläge)

raf_eins_mem

# Nun wird das Netzwerk der Mitglieder der 2. Generation geplottet:
plot(raf_eins_mem,
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     edge.curved=curve_multiple(raf_eins_mem), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="Netzwerk der ersten Generation mit Unterstützer*innen",
     sub="1.Generation = hellgrau / Beide Generationen = weiß / Unterstützer*innen = hellrosa")

```

```{r 1. Generation mit Mitgliedern und Anschlägen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

# Zuletzt betrachten wir nur die Mitglieder und Anschläge der ersten Generation ohne Unterstützer*innen (harter Kern)
raf_eins

raf_eins_pur <- delete_vertices(raf_eins, V(raf_eins)[generation =="4"]) # löscht alle Knoten, für die der Wert von Generation 4 beträgt, damit bleiben diejenigen, die der RAF angehört haben 

plot(raf_eins_pur,
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     edge.curved=curve_multiple(raf_eins_pur), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="Netzwerk der Mitglieder der ersten Generation",
     sub="1.Generation = hellgrau / Beide Generationen = weiß / Anschläge = quadratisch und blau" )


```



##Betrachten der zweiten Generation

```{r 2. Generation mit Anschlägen und Unterstützer*innen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

# Wir schauen uns das Netzwerk der zweiten Generation mit Anschlägen und Unterstützer*innen an:

raf

raf_zwei <- delete_vertices(raf, V(raf)[generation =="1"]) # löscht alle Knoten, für die der Wert von Generation 1 beträgt, damit bleiben diejenigen, die der zweiten und beider Generationen angehört haben. 
V(raf_zwei)[V(raf_zwei)$generation == "2"]$color <- "grey30" # Knoten der Mitglieder der 2. Generation werden in Farbe grey30 dargestellt
V(raf_zwei)[V(raf_zwei)$generation == 3]$color <- "white" # Knoten der Mitglieder beider Generation werden weiß eingefärbt
V(raf_zwei)[V(raf_zwei)$generation == 4]$color <- "lightpink" # Knoten der Unterstützer*innen werden hellrosa eingefärbt
V(raf_zwei)[V(raf_zwei)$type == 1]$shape <- "circle" # Personen werden als Kreise dargestellt
V(raf_zwei)[V(raf_zwei)$type == 2]$shape <- "square" # Aktionen werden als Quadrate dargestellt
V(raf_zwei)[V(raf_zwei)$type == 2]$color <- "cornflowerblue" # Knoten der Aktionen werden kornblumenblau gefärbt


raf_zwei

plot(raf_zwei,
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     edge.curved=curve_multiple(raf_zwei), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="Netzwerk der zweiten Generation mit Anschlägen",
     sub="2.Generation = dunkelgrau / Beide Generationen = weiß / Unterstützer*innen = hellrosa / Anschläge = quadratisch und blau")

```

```{r 2. Generation - nur Personen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

# Nun lassen wir uns nur die Personen der zweiten Generation anzeigen - ohne Anschläge

raf_zwei

raf_zwei_mem <- delete_vertices(raf_zwei, V(raf_zwei)[type !="1"])# Wir löschen alle Knoten, die als Typ den Wert 1 haben (=Anschläge)

raf_zwei_mem

# Nun wird das Netzwerk der Mitglieder der 2. Generation geplottet:
plot(raf_zwei_mem,
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     edge.curved=curve_multiple(raf), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="Netzwerk der zweiten Generation mit Unterstützer*innen",
     sub="2.Generation = dunkelgrau / Beide Generationen = weiß / Unterstützer*innen = hellrosa")

```

```{r 2. Generation mit Mitgliedern und Anschlägen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

# Zuletzt betrachten wir nur die Mitglieder und Anschläge der zweiten Generation ohne Unterstützer*innen (harter Kern)
raf_zwei

raf_zwei_pur <- delete_vertices(raf_zwei, V(raf_zwei)[generation =="4"]) # löscht alle Knoten, für die der Wert von Generation 4 beträgt (Unterstützer*innen), damit bleiben die Mitglieder der RAF. 

plot(raf_zwei_pur,
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     edge.curved=curve_multiple(raf_zwei_pur), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="Netzwerk der Mitglieder der zweiten Generation",
     sub="2.Generation = dunkelgrau / Beide Generationen = weiß / Anschläge = quadratisch und blau" )


```

##Gründungsmitglieder
```{r Hervorheben der Gründungsmitglieder, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

#In diesem Schritt heben wir die Gründungsmitglieder im Gesamtnetzwerk rot hervor:

raf

raf_founding <- delete_vertices(raf, V(raf)[type !="1"]) #löschen der Anschläge

V(raf_founding) [V(raf_founding)$type == 1]$color <- "white" #Knoten weiß einfärben
V(raf_founding)[V(raf_founding)$foundingmember == 1]$color <- "firebrick" #Gründungsmitglieder rot einfärben

plot(raf_founding,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Gesamtnetzwerk der Personen",
     sub="Gründungsmitglieder rot hervorgehoben")


```

```{r Netzwerk der Gründungsmitglieder, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

#Wir visualisieren das Netzwerk der Gründungsmitglieder

raf_founding

raf_foundingmember <- delete.vertices(raf_founding, V(raf_founding)[foundingmember !="1"]) #löschen der Mitglieder nach der Gründung


plot(raf_foundingmember,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=10,
     edge.curved=curve_multiple(raf_foundingmember), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label.family="sans",
     vertex.label.cex=1,
     vertex.label.color="black",
     main="Gründungsmitglieder")

```

```{r Geschlechterverteilung Gründungsmitglieder, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

raf_foundingmember
sex <- raf_foundingmember
V(sex) [V(raf_foundingmember)$sex == 1]$color <- "darkseagreen" #Knoten weiß einfärben
V(sex)[V(raf_foundingmember)$sex == 2]$color <- "darkorange3" #

plot(sex,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=10,
     edge.curved=curve_multiple(raf_foundingmember), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label.family="sans",
     vertex.label.cex=1,
     vertex.label.color="black",
     main="Gründungsmitglieder nach Geschlecht",
     sub="Grün = Männlich / Orange = Weiblich")
```
```{r Anteil Gründungsmitglieder 1.Generation, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

raf_eins_pur

founding_eins <-  delete_vertices(raf_eins_pur, V(raf_eins_pur)[type !="1"]) #löschen der Anschläge

V(founding_eins) [V(founding_eins)$type == 1]$color <- "white" #Knoten weiß einfärben
V(founding_eins)[V(founding_eins)$foundingmember == 1]$color <- "firebrick" #Gründungsmitglieder rot einfärben

plot(founding_eins,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Mitglieder der ersten Generation",
     sub="Gründungsmitglieder rot hervorgehoben")
```

## Ausbildungsgrad
```{r Ausbildungsgrad aller Mitglieder, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

# Wir betrachten den Ausbildungsgrad der einzelnen Mitglieder
raf

raf_edu <- delete_vertices(raf, V(raf)[type !="1"]) # löscht alle Anschläge

# Veränderung der Füllfarbe der Vertices je nach Ausbildungsgrad
V(raf_edu)[V(raf_edu)$education == 1]$color <- "black" # kein Abschluss wird schwarz gefärbt
V(raf_edu)[V(raf_edu)$education == 2]$color <- "lightseagreen" # Hauptschulabsolventen grün einfärben
V(raf_edu)[V(raf_edu)$education == 3]$color <- "darkgoldenrod1" # Realschulabsolventen dunkelgelb einfräben
V(raf_edu)[V(raf_edu)$education == 4]$color <- "cornflowerblue" # Gymnasialabsolventen hellblau einfärben
V(raf_edu)[V(raf_edu)$education == 5]$color <- "darkslateblue" # Hochschulabsolventen dunkelblau einfärben
V(raf_edu)[V(raf_edu)$education == 99]$color <- "white" # Knoten, zu denen es keine Angabe gibt, werden weiß gefärbt

raf_edu

plot(raf_edu,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Einfärbung nach Bildungsgrad",
     sub="Weiß = Keine Angabe / Schwarz = Kein Abschluss / Grün = Hauptschulabschluss / Gelb = Realschulabschluss / Hellblau = Abitur / Dunkelblau = Hochschulabschluss")

```
```{r Ausbildungsgrad beider Generationen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

#Jetzt wollen wir den Ausbildungsgrad beider Generationen vergleichen

#Zuerst schauen wir dazu die erste Generation an:
raf_eins_mem

raf_edu_eins <- raf_eins_mem

# Veränderung der Füllfarbe der Vertices je nach Ausbildungsgrad
V(raf_edu_eins)[V(raf_edu_eins)$education == 1]$color <- "black" # kein Abschluss wird schwarz gefärbt
V(raf_edu_eins)[V(raf_edu_eins)$education == 2]$color <- "lightseagreen" # Hauptschulabsolventen grün einfärben
V(raf_edu_eins)[V(raf_edu_eins)$education == 3]$color <- "darkgoldenrod1" # Realschulabsolventen dunkelgelb einfräben
V(raf_edu_eins)[V(raf_edu_eins)$education == 4]$color <- "cornflowerblue" # Gymnasialabsolventen hellblau einfärben
V(raf_edu_eins)[V(raf_edu_eins)$education == 5]$color <- "darkslateblue" # Hochschulabsolventen dunkelblau einfärben
V(raf_edu_eins)[V(raf_edu_eins)$education == 99]$color <- "white" # Knoten, zu denen es keine Angabe gibt, werden weiß gefärbt

raf_edu_eins

plot(raf_edu_eins,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf_edu_eins), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="1. Generation - Einfärbung nach Bildungsgrad",
     sub="Weiß = Keine Angabe / Schwarz = Kein Abschluss / Grün = Hauptschulabschluss / Gelb = Realschulabschluss / Hellblau = Abitur / Dunkelblau = Hochschulabschluss")

#Nun schauen wir uns die zweite Generation an:

raf_zwei_mem

raf_edu_zwei <- raf_zwei_mem

# Veränderung der Füllfarbe der Vertices je nach Ausbildungsgrad
V(raf_edu_zwei)[V(raf_edu_zwei)$education == 1]$color <- "black" # kein Abschluss wird schwarz gefärbt
V(raf_edu_zwei)[V(raf_edu_zwei)$education == 2]$color <- "lightseagreen" # Hauptschulabsolventen grün einfärben
V(raf_edu_zwei)[V(raf_edu_zwei)$education == 3]$color <- "darkgoldenrod1" # Realschulabsolventen dunkelgelb einfräben
V(raf_edu_zwei)[V(raf_edu_zwei)$education == 4]$color <- "cornflowerblue" # Gymnasialabsolventen hellblau einfärben
V(raf_edu_zwei)[V(raf_edu_zwei)$education == 5]$color <- "darkslateblue" # Hochschulabsolventen dunkelblau einfärben
V(raf_edu_zwei)[V(raf_edu_zwei)$education == 99]$color <- "white" # Knoten, zu denen es keine Angabe gibt, werden weiß gefärbt

raf_edu_zwei

plot(raf_edu_zwei,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf_edu_zwei), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="2. Generation - Einfärbung nach Bildungsgrad",
     sub="Weiß = Keine Angabe / Schwarz = Kein Abschluss / Grün = Hauptschulabschluss / Gelb = Realschulabschluss / Hellblau = Abitur / Dunkelblau = Hochschulabschluss")


```

## Berufsfelder
```{r Einfärben der Berufsfelder, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE }

raf

raf_job <- delete_vertices(raf, V(raf)[type !="1"]) # löscht alle Anschläge )

V(raf_job)[V(raf_job)$job == 1]$color <- "burlywood" # Journalist*innen hellbraun einfärben
V(raf_job)[V(raf_job)$job == 2]$color <- "cornflowerblue" # Lehrer*innen etc blau einfärben
V(raf_job)[V(raf_job)$job == 3]$color <- "olivedrab3" # Jurist*innen grün einfärben
V(raf_job)[V(raf_job)$job == 4]$color <- "white" # Sonstige Berufsgruppe orange einfärben
V(raf_job)[V(raf_job)$job == 5]$color <- "plum3" # Studierende rosa einfärben
V(raf_job)[V(raf_job)$job == 6]$color <- "black" # Kunstschaffende schwarz einfärben
V(raf_job)[V(raf_job)$job == 99]$color <-"white"# ohne Angabe weiß einfärben
plot(raf_job,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf_job), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Einfärbung nach Berufsfeld",
     sub="Blau = Pädagogik / Dunkelrosa = Studierende / Grün = Jurist*innen / Hellbraun = Journalist*innen / Weiß = Andere Berufsfelder/keine Angabe")


```

```{r Berufsfelder nach Generationen, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

#Zuerst betrachten wir die erste Generation:

raf_eins_mem

job_eins <- raf_eins_mem

V(job_eins)[V(job_eins)$job == 1]$color <- "burlywood" # Journalist*innen hellbraun einfärben
V(job_eins)[V(job_eins)$job == 2]$color <- "cornflowerblue" # Lehrer*innen etc blau einfärben
V(job_eins)[V(job_eins)$job == 3]$color <- "olivedrab3" # Jurist*innen grün einfärben
V(job_eins)[V(job_eins)$job == 4]$color <- "white" # Sonstige Berufsgruppe orange einfärben
V(job_eins)[V(job_eins)$job == 5]$color <- "plum3" # Studierende rosa einfärben
V(job_eins)[V(job_eins)$job == 6]$color <- "black" # Kunstschaffende schwarz einfärben
V(job_eins)[V(job_eins)$job == 99]$color <-"white"# ohne Angabe weiß einfärben
plot(job_eins,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(job_eins), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main=" 1. Generation - Einfärbung nach Berufsfeld",
     sub="Blau = Pädagogik / Dunkelrosa = Studierende / Grün = Jurist*innen / Hellbraun = Journalist*innen / Weiß = Andere Berufsfelder/keine Angabe")

#Dann die zweite Generation:

raf_zwei_mem

job_zwei <- raf_zwei_mem

V(job_zwei)[V(job_zwei)$job == 1]$color <- "burlywood" # Journalist*innen hellbraun einfärben
V(job_zwei)[V(job_zwei)$job == 2]$color <- "cornflowerblue" # Lehrer*innen etc blau einfärben
V(job_zwei)[V(job_zwei)$job == 3]$color <- "olivedrab3" # Jurist*innen grün einfärben
V(job_zwei)[V(job_zwei)$job == 4]$color <- "white" # Sonstige Berufsgruppe orange einfärben
V(job_zwei)[V(job_zwei)$job == 5]$color <- "plum3" # Studierende rosa einfärben
V(job_zwei)[V(job_zwei)$job == 6]$color <- "black" # Kunstschaffende schwarz einfärben
V(job_zwei)[V(job_zwei)$job == 99]$color <-"white"# ohne Angabe weiß einfärben

plot(job_zwei,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(job_zwei), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main=" 2. Generation - Einfärbung nach Berufsfeld",
     sub="Blau = Pädagogik / Dunkelrosa = Studierende / Grün = Jurist*innen / Hellbraun = Journalist*innen / Weiß = Andere Berufsfelder/keine Angabe")


```

##Geschlechter
```{r Geschlechterverteilung Gesamtnetzwerk, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

#Wir betrachten die Geschlechterverteilung des Gesamtnetzwerks:
raf

raf_sex <- delete.vertices(raf, V(raf)[type == 2])#löscht alle Anschläge

V(raf_sex) [V(raf_sex)$sex == 1]$color <- "darkseagreen" #Knoten mit Attribut "männlich" grün einfärben
V(raf_sex)[V(raf_sex)$sex == 2]$color <- "darkorange3" #Knoten mit Attribut "weiblich" orange einfärben

plot(raf_sex,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf_sex), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Geschlechterverteilung gesamt",
     sub="Grün = Männlich / Orange = Weiblich")

```

```{r Geschlechterverteilung 1.Generation, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

#Nun schauen wir die Geschlechterverteilung der ersten Generation an:

raf_eins_mem

raf_sex_eins <- raf_eins_mem

V(raf_sex_eins) [V(raf_sex_eins)$sex == 1]$color <- "darkseagreen" #Knoten grün einfärben
V(raf_sex_eins)[V(raf_sex_eins)$sex == 2]$color <- "darkorange3" #Knoten orange einfärben

plot(raf_sex_eins,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf_sex_eins), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="1. Generation - Geschlechterverteilung",
     sub="Grün = Männlich / Orange = Weiblich")

```
```{r Geschlechterverteilung 2.Generation, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, paged.print=FALSE}

#Zuletzt schauen wir die Geschlechterverteilung der zweiten Generation an:

raf_zwei_mem

raf_sex_zwei <- raf_zwei_mem

V(raf_sex_zwei) [V(raf_sex_zwei)$sex == 1]$color <- "darkseagreen" #Knoten grün einfärben
V(raf_sex_zwei)[V(raf_sex_zwei)$sex == 2]$color <- "darkorange3" #Knoten orange einfärben

plot(raf_sex_zwei,
     layout=layout_with_kk,
     asp=0, # definiert, dass der ganze Platz ausgenutzt werden soll
     vertex.size=5,
     edge.curved=curve_multiple(raf_sex_zwei), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="2. Generation - Geschlechterverteilung",
     sub="Grün = Männlich / Orange = Weiblich")

```



