
```{r wichtigste packages abrufen}

#wir laden nun vorab die wichtigsten packages
library(igraph)
library(igraphdata)
library(knitr) 
library(rmarkdown) 
```

```{r Gesamtnetzwerk einlesen}

# Wir lesen das Netzwerk im Folgenden ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# Visualisierung des Netzwerks
plot(raf,
     layout=layout_with_kk,
     edge.curved=curve_multiple(raf), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="RAF-Gesamtnetzwerk der RAF",
     sub="erste und zweite Generation")

```

```{r Visualisierung nach Knotentypen}

# Wir lesen das Netzwerk im Folgenden ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

#Grafisch werden Ereignisse/Aktionen  anders dargestellt als Akteure
V(raf)[V(raf)$type == 1]$shape <- "circle" # Personen als Kreise
V(raf)[V(raf)$type == 2]$shape <- "square" # Aktionen als Quadrate
V(raf)[V(raf)$type == 1]$color <- "red" # Personen rot einfärben
V(raf)[V(raf)$type == 2]$color <- "orange" #Aktionen orange einfärben

# Visualisierung des Netzwerks nach Knotentypen
plot(raf,
     layout=layout_with_kk,
     edge.curved=curve_multiple(raf), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="RAF-Gesamtnetzwerk nach Knotentypen",
     sub="Kreis = Person, Aktion = Quadrat")

```

```{r Visualisierung nach Generationen}
raf

V(raf)[V(raf)$generation == 1]$color <- "red" # Personen rot einfärben
V(raf)[V(raf)$generation == 2]$color <- "orange" #Aktionen orange einfärben
V(raf)[V(raf)$generation == 3]$color <- "pink" # Personen rot einfärben
V(raf)[V(raf)$type == 2]$color <- "black" # Aktionen schwarz einfärben

# Visualisierung des Netzwerks nach Generationen
plot(raf,
     layout=layout_with_kk,
     edge.curved=curve_multiple(raf), # verhindert, dass sich Kanten überlagern
     vertex.label=NA, # entfernt die Beschriftung der Knoten für bessere Übersichtlichkeit
     vertex.size=5,
     main="RAF-Gesamtnetzwerk nach Generationen",
     sub="Mitglieder der verschiedenen Generationen werden unterschiedlich eingefärbt. 
     Erste Generation = rot, Zweite Generation = orange, Beide Generationen = pink, Aktionen =  
     schwarz")
```

```{r Teilnetzwerk der ersten Generation}

raf
# Zeigt uns die Vertex-Attribute des Gesamtnetzwerks "raf" an.
vertex_attr(raf)

# Wir wollen nun wissen, wie das Netzwerk der ersten Generation der RAF aussieht:
raf_eins <- delete_vertices(raf, V(raf)[generation !="1"]) # löscht alle Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der ersten Generation angehört haben. 

#raf_eins <- add.vertices(raf, V(raf)[generation !="3"]) # Da im Codebuch neben Akteuren, die der ersten und zweiten Generation angehört haben, auch Akteure, die beiden Generationen angehört haben, definiert sind, sollen diese dem Netzwerk wieder hinzugefügt werden. Im Schritt zuvor wurden diese ja mit herausgelöscht, da nur Knoten mit dem Wert generation = 1 behalten wurden, aber wer beiden Generationen angehört hat (generation = 1), muss natürlich auch dem Netzwerk der 1. Generation hinzugefügt werden. !! Notiz: eigentlich wichtiger Befehl, aber irgendeinwie plottet es damit gerade nicht, deshalb vorübergehend deaktiviert, bis ich eine Lösung gefunden habe

raf_eins
vertex_attr(raf_eins)

# um das Netzwerk der ersten Generation anzuzeigen, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
raf_eins_mem <- delete_vertices(raf_eins, V(raf_eins)[type !="1"])

raf_eins_mem

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(raf_eins_mem) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-0.75, ymax=0.75, xmin=-0.75, xmax=0.75)

#par(mfrow=c(2,2), mar=c(3,3,3,3)) #Austesten verschiedener Layout-Optionen
#plot(raf_eins, rescale=F, layout=l*0.4)
#plot(raf_eins, rescale=F, layout=l*0.8)
#plot(raf_eins, rescale=F, layout=l*1.2)
#plot(raf_eins, rescale=F, layout=l*1.6)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Netzwerk der Mitglieder der 1. Generation geplottet:
plot(raf_eins_mem, 
     rescale=F, 
     layout=l*1.2,
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.color="red",
     vertex.size=5,
     edge.curved=curve_multiple(raf_eins_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Netzwerk der ersten Generation")
     
```
```{r Teilnetzwerk der zweiten Generation}
raf
# Zeigt uns die Vertex-Attribute des Gesamtnetzwerks "raf" an.
vertex_attr(raf)

# Wir wollen nun wissen, wie das Netzwerk der ersten Generation der RAF aussieht:
raf_zwei <- delete_vertices(raf, V(raf)[generation !="2"]) # löscht alle Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der ersten Generation angehört haben. 

#raf_eins <- add.vertices(raf, V(raf)[generation !="3"]) # Da im Codebuch neben Akteuren, die der ersten und zweiten Generation angehört haben, auch Akteure, die beiden Generationen angehört haben, definiert sind, sollen diese dem Netzwerk wieder hinzugefügt werden. Im Schritt zuvor wurden diese ja mit herausgelöscht, da nur Knoten mit dem Wert generation = 1 behalten wurden, aber wer beiden Generationen angehört hat (generation = 1), muss natürlich auch dem Netzwerk der 1. Generation hinzugefügt werden. !! Notiz: eigentlich wichtiger Befehl, aber irgendeinwie plottet es damit gerade nicht, deshalb vorübergehend deaktiviert, bis ich eine Lösung gefunden habe

raf_zwei
vertex_attr(raf_zwei)

# um das Netzwerk der zweiten Generation anzuzeigen, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
raf_zwei_mem <- delete_vertices(raf_zwei, V(raf_zwei)[type !="1"])

raf_zwei_mem

#Entzerrte Darstellung, Anpassung der Visualisierung 
l <- layout_with_kk(raf_zwei_mem) #legt den Layout-Typ fest
l <- norm_coords(l, ymin=-0.75, ymax=0.75, xmin=-0.75, xmax=0.75)

#par(mfrow=c(2,2), mar=c(3,3,3,3)) #Austesten verschiedener Layout-Optionen
#plot(raf_eins, rescale=F, layout=l*0.4)
#plot(raf_eins, rescale=F, layout=l*0.8)
#plot(raf_eins, rescale=F, layout=l*1.2)
#plot(raf_eins, rescale=F, layout=l*1.6)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Netzwerk der Mitglieder der 1. Generation geplottet:
plot(raf_zwei_mem, 
     rescale=F, 
     layout=l*1.2,
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.color="red",
     vertex.size=5,
     edge.curved=curve_multiple(raf_zwei_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Netzwerk der zweiten Generation")
 
```


```{r Hervorheben der Gründungsmitglieder}

# Nun wollen wir visualisieren, wo die Gründungsmitglieder im Gesamtnetzwerk zu verorten sind.

# Wir lesen das Netzwerk dazu im Folgenden neu ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)

raf

#alle Knoten, bei denen es sich nicht um natürliche Personen (ergo, alle Anschläge) werden gelöscht
delete_vertices(raf, V(raf)[type !="1"]) 

V(raf)[V(raf)$foundingmember == 1]$color <- "red" # Gründungsmitglieder rot einfärben

plot(raf,
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Netzwerk der ersten und zweiten Generation",
     sub="Gründungsmitglieder rot hervorgehoben")


```

```{r Gründungsmitglieder im Netzwerk der ersten Generation hervorheben}

# nun fokussieren wir uns auf das Netzwerk der ersten Generation, da die Gründungsmitglieder diese ja schließlich begründet haben und wollen uns deren Position im Netzwerk genauer ansehen.

# Dazu erstellen wir erneut das Teilnetzwerk der ersten Generation
raf_eins <- delete_vertices(raf, V(raf)[generation !="1"]) # löscht alle Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der ersten Generation angehört haben. 

#raf_eins <- add.vertices(raf, V(raf)[generation !="3"]) # Da im Codebuch neben Akteuren, die der ersten und zweiten Generation angehört haben, auch Akteure, die beiden Generationen angehört haben, definiert sind, sollen diese dem Netzwerk wieder hinzugefügt werden. Im Schritt zuvor wurden diese ja mit herausgelöscht, da nur Knoten mit dem Wert generation = 1 behalten wurden, aber wer beiden Generationen angehört hat (generation = 1), muss natürlich auch dem Netzwerk der 1. Generation hinzugefügt werden. !! Notiz: eigentlich wichtiger Befehl, aber irgendeinwie plottet es damit gerade nicht, deshalb vorübergehend deaktiviert, bis ich eine Lösung gefunden habe

raf_eins

# um das Netzwerk der ersten Generation anzuzeigen, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
raf_eins_mem <- delete_vertices(raf_eins, V(raf_eins)[type !="1"])

raf_eins_mem
raf_eins_mem

V(raf_eins_mem)[V(raf_eins_mem)$foundingmember == 1]$color <- "red" # Gründungsmitglieder rot einfärben

plot(raf_eins_mem, 
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_eins_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Netzwerk der ersten Generation",
     sub="Gründungsmitglieder rot hervorgehoben")
```

```{r Gesamt- und Teilnetzwerk der ersten Generation gegenüberstellen}

par(mfrow=c(1,2), mar=c(0,0,2,1)) # definiert, dass zwei Abbildungen in einer Zeile stehen


plot(raf,
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Gesamtnetzwerk",
     sub="Gründungsmitglieder rot hervorgehoben")

plot(raf_eins_mem, 
     edge.color="grey80",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_eins_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Erste Generation",
     sub="Gründungsmitglieder rot hervorgehoben")

```
```{r Ausgetretene Mitglieder}

# wir lesen das Gesamtnetzwerk neu ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# da es um ausgetretene Mitglieder geht, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
raf_pers <- delete_vertices(raf, V(raf)[type !="1"])

# außerdem sollen alle Knoten gelöscht werden, die kein Mitglied der RAF waren, da diese dann ja logischerweise auch nicht austreten können. 
raf_mem <- delete_vertices(raf_pers, V(raf_pers)[membership !="1"])
raf_mem

# Nun soll die Darstellung der Mitglieder angepasst werden, je nachdem ob sie ausgetreten sind oder nicht
# im Codebuch sind für das Vertex-Attribut resignation folgende Werte definiert
# 1 = Austritt / Rückzug 2 = nein, kein Austritt, 3 = bis zum Tod Mitglied, 99 = keine Angabe gefunden

V(raf_mem)[V(raf_mem)$resignation == 99]$color <- "white" # Knoten, zu denen es keine Angabe gibt, bleiben weiß
V(raf_mem)[V(raf_mem)$resignation == 1]$color <- "red" # Alle Mitglieder, die ausgetreten sind, schwarz einfärben
V(raf_mem)[V(raf_mem)$resignation == 2]$color <- "black" # Dauerhafte Mitglieder schwarz einfärben
V(raf_mem)[V(raf_mem)$resignation == 3]$color <- "orange" # Alle, die bis zum Tod Mitglied waren, orange einfärben

plot(raf_mem,
     edge.color="grey80",
     layout=layout_with_kk,
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Netzwerk der ersten und zweiten Generation - Ausgetretene Mitglieder",
     sub="rot = Austritt/Rückzug, schwarz = kein Austritt, 
     orange = Mitglied bis zum Tod, weiß = keine Angabe gefunden")


```
```{r Vergleich der Austritte in den Generationen}

raf_mem

# Wir wollen nun wissen, wie das Netzwerk der ersten Generation der RAF aussieht:
raf_eins_mem <- delete_vertices(raf_mem, V(raf_mem)[generation !="1"]) # löscht alle RAF-Mitglieder bzw. Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der ersten Generation angehört haben. 

raf_eins_mem

# Wir wollen nun wissen, wie das Netzwerk der zweiten Generation der RAF aussieht:
raf_zwei_mem <- delete_vertices(raf_mem, V(raf_mem)[generation !="2"]) # löscht alle Raf-Mitglieder bzw. Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der zweiten Generation angehört haben. 

raf_zwei_mem

par(mfrow=c(1,2), mar=c(0,0,2,1)) # definiert, dass zwei Abbildungen in einer Zeile stehen

raf_eins_mem

plot(raf_eins_mem, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_eins_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Erste Generation",
     sub="rot = Austritt/Rückzug, schwarz = kein Austritt, 
     orange = Mitglied bis zum Tod, weiß = keine Angabe gefunden")

plot(raf_zwei_mem, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_zwei_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Zweite Generation",
     sub="rot = Austritt/Rückzug, schwarz = kein Austritt, 
     orange = Mitglied bis zum Tod, weiß = keine Angabe gefunden")
```
```{r symbolic death}

# Nun sollen die Mitglieder hervorgehoben werden, die noch während ihrer aktiven Mitgliedschaft gestorben sind, bei einem Schusswechsel oder durch Suizid

# wir lesen das Gesamtnetzwerk neu ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# da es um ausgetretene Mitglieder geht, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
raf_pers <- delete_vertices(raf, V(raf)[type !="1"])

# außerdem sollen alle Knoten gelöscht werden, die kein Mitglied der RAF waren, da diese dann ja logischerweise auch nicht austreten können. 
raf_mem <- delete_vertices(raf_pers, V(raf_pers)[membership !="1"])
raf_mem

# Nun soll die Darstellung der Mitglieder angepasst werden, je nachdem ob sie ausgetreten sind oder nicht
# im Codebuch sind für das Vertex-Attribut resignation folgende Werte definiert
# 1 = Austritt / Rückzug 2 = nein, kein Austritt, 3 = bis zum Tod Mitglied, 99 = keine Angabe gefunden

# Veränderung der Füllfarbe des Vertex
V(raf_mem)$color <- "white" # zur Abgrenzung sollen alle Knoten, die keinen symbolischen Tod hatten oder keine Angabe dazu vorliegt, weiß gefärbt werden
V(raf_mem)[V(raf_mem)$symbolicdeath == 99]$color <- "red" # symbolic deaths rot hervorheben

plot(raf_mem,
     edge.color="grey80",
     layout=layout_with_kk,
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung,
     main="Netzwerk der ersten und zweiten Generation - Symbolischer Tod",
     sub="rot = symbolischer Tod, weiß = keine Angabe gefunden oder kein symbolischer Tod")


```
```{r symbolic death - Vergleich der zwei Generationen}
raf_mem

# Wir wollen nun wissen, wie das Netzwerk der ersten Generation der RAF aussieht:
raf_eins_mem <- delete_vertices(raf_mem, V(raf_mem)[generation !="1"]) # löscht alle RAF-Mitglieder bzw. Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der ersten Generation angehört haben. 

# Veränderung der Füllfarbe des Vertex
V(raf_eins_mem)$color <- "white" # zur Abgrenzung sollen alle Knoten, die keinen symbolischen Tod hatten oder keine Angabe dazu vorliegt, weiß gefärbt werden
V(raf_eins_mem)[V(raf_eins_mem)$symbolicdeath == 99]$color <- "red" # symbolic deaths rot hervorheben

raf_eins_mem


# Wir wollen nun wissen, wie das Netzwerk der zweiten Generation der RAF aussieht:
raf_zwei_mem <- delete_vertices(raf_mem, V(raf_mem)[generation !="2"]) # löscht alle Raf-Mitglieder bzw. Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der zweiten Generation angehört haben. 

# Veränderung der Füllfarbe des Vertex
V(raf_zwei_mem)$color <- "white" # zur Abgrenzung sollen alle Knoten, die keinen symbolischen Tod hatten oder keine Angabe dazu vorliegt, weiß gefärbt werden
V(raf_zwei_mem)[V(raf_zwei_mem)$symbolicdeath == 99]$color <- "red" # symbolic deaths rot hervorheben

raf_zwei_mem

par(mfrow=c(1,2), mar=c(0,0,2,1)) # definiert, dass zwei Abbildungen in einer Zeile stehen

raf_eins_mem

plot(raf_eins_mem, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_eins_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Erste Generation",
     sub="rot = symbolischer Tod, weiß = keine Angabe gefunden oder kein symbolischer Tod")

plot(raf_zwei_mem, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_zwei_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Zweite Generation",
     sub="rot = symbolischer Tod, weiß = keine Angabe gefunden oder kein symbolischer Tod")
```

```{r Ausbildungsgrad einfärben}

# wir lesen das Gesamtnetzwerk neu ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# da es um den Ausbildungsgrad der Personen geht, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
delete_vertices(raf, V(raf)[type !="1"])

# Nun sollen die Knoten je nach ihrem Abschluss unterschiedlich eingefärbt werden
# im Codebuch gibt es dazu folgende Codierung: das Vertext-Attribut education hat folgende Werte: 1 = kein Abschluss, 2 = Hauptschulabschluss, 3 = mittlere Reife, 4 = Gymnasialabschluss, 5 = Hochschulabschluss

V(raf)[V(raf)$education == 1]$color <- "black" # kein Abschluss wird schwarz gefärbt
V(raf)[V(raf)$education == 2]$color <- "red" # Hauptschulabsolventen rot einfärben
V(raf)[V(raf)$education == 3]$color <- "orange" # Realschulabsolventen orange einfräben
V(raf)[V(raf)$education == 4]$color <- "lightgreen" # Gymnasialabsolventen hellgrün einfärben
V(raf)[V(raf)$education == 5]$color <- "darkgreen" # Hochschulabsolventen dunkelgrün einfärben
V(raf)[V(raf)$education == 99]$color <- "white" # Knoten, zu denen es keine Angabe gibt, werden weiß gefärbt

# Visualisierung des Gesamtnetzwerks der Mitglieder nach Ausbildungsgrad
plot(raf, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Netzwerk der ersten und zweiten RAF-Generation nach Ausbildungsgrad",
     sub="schwarz = kein Abschluss, rot = Hauptschulabschluss, orange = mittlere Reife, 
     hellgrün = Gymnasialabschluss, dunkelgrün = Hochschulabschluss, weiß = keine Angabe")

```

```{r Teilnetzwerke mit Vergleich des Ausbildungsgrades}

# um zu sehen, ob es Unterschiede in der Verteilung der Bildungsabschlüsse zwischen den beiden Generationen (1 und 2) gab, sollen diese nun als Teilnetzwerke verglichen werden
raf

# Wir wollen nun wissen, wie das Netzwerk der ersten Generation der RAF aussieht:
raf_eins <- delete_vertices(raf, V(raf)[generation !="1"]) # löscht alle RAF-Mitglieder bzw. Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der ersten Generation angehört haben. 

# Veränderung der Füllfarbe der Vertices der 1. Generation je nach Ausbildungsgrad
V(raf_eins)[V(raf_eins)$education == 1]$color <- "black" # kein Abschluss wird schwarz gefärbt
V(raf_eins)[V(raf_eins)$education == 2]$color <- "red" # Hauptschulabsolventen rot einfärben
V(raf_eins)[V(raf_eins)$education == 3]$color <- "orange" # Realschulabsolventen orange einfräben
V(raf_eins)[V(raf_eins)$education == 4]$color <- "lightgreen" # Gymnasialabsolventen hellgrün einfärben
V(raf_eins)[V(raf_eins)$education == 5]$color <- "darkgreen" # Hochschulabsolventen dunkelgrün einfärben
V(raf_eins)[V(raf_eins)$education == 99]$color <- "white" # Knoten, zu denen es keine Angabe gibt, werden weiß gefärbt

raf_eins

# Wir wollen nun wissen, wie das Netzwerk der zweiten Generation der RAF aussieht:
raf_zwei <- delete_vertices(raf, V(raf)[generation !="2"]) # löscht alle Raf-Mitglieder bzw. Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der zweiten Generation angehört haben. 

# Veränderung der Füllfarbe der Vertices der 2. Generation je nach Ausbildungsgrad
V(raf_zwei)[V(raf_zwei)$education == 1]$color <- "black" # kein Abschluss wird schwarz gefärbt
V(raf_zwei)[V(raf_zwei)$education == 2]$color <- "red" # Hauptschulabsolventen rot einfärben
V(raf_zwei)[V(raf_zwei)$education == 3]$color <- "orange" # Realschulabsolventen orange einfräben
V(raf_zwei)[V(raf_zwei)$education == 4]$color <- "lightgreen" # Gymnasialabsolventen hellgrün einfärben
V(raf_zwei)[V(raf_zwei)$education == 5]$color <- "darkgreen" # Hochschulabsolventen dunkelgrün einfärben
V(raf_zwei)[V(raf_zwei)$education == 99]$color <- "white" # Knoten, zu denen es keine Angabe gibt, werden weiß gefärbt
raf_zwei

par(mfrow=c(1,2), mar=c(0,0,2,1)) # definiert, dass zwei Abbildungen in einer Zeile stehen

raf_eins

plot(raf_eins, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_eins), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Erste Generation",
     sub="schwarz = kein Abschluss, rot = Hauptschulabschluss, orange = mittlere Reife, 
     hellgrün = Gymnasialabschluss, dunkelgrün = Hochschulabschluss")

plot(raf_zwei, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_zwei), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Zweite Generation",
     sub="schwarz = kein Abschluss, rot = Hauptschulabschluss, orange = mittlere Reife, 
     hellgrün = Gymnasialabschluss, dunkelgrün = Hochschulabschluss")

```


```{r Hervorheben der Mitglieder aus gläubig-geprägtem Elternhaus}

# wir lesen das Gesamtnetzwerk neu ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# da es um das Elternhaus der Personen geht, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
delete_vertices(raf, V(raf)[type !="1"])

# Nun sollen die Knoten je nach religiöser Prägung in ihrem Elternhaus unterschiedlich eingefärbt werden
# im Codebuch gibt es dazu folgende Codierung: das Vertext-Attribut upbringing hat folgende Werte: 1 = Pfarrer*in bzw. Pastor*in im Elternhaus, 2 = kein Pfarrer*in / Priester*in im Elternhaus, 99 = keine Angabe gefunden

V(raf)[V(raf)$upbringing == 1]$color <- "red" # kein Abschluss wird schwarz gefärbt
V(raf)[V(raf)$upbringing == 2]$color <- "black" # Hauptschulabsolventen rot einfärben
V(raf)[V(raf)$upbringing == 99]$color <- "white" # Knoten, zu denen es keine Angabe gibt, werden weiß gefärbt
# die letzten zwei Zeilen könnte man auch durch einen Kommentar "ausschalten", da es auch ausreichen würde, nur die tatsächlichen Pfarrerskinder zu highlighten. Dazu müsste dann noch die Unterüberschrift des Plots angepasst werden, sodass dort in der Legende nur steht "rot = ..."

# Visualisierung des Gesamtnetzwerks der Mitglieder nach Elternhaus
plot(raf, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Pfarrerskinder im Netzwerk der ersten und zweiten RAF-Generation",
     sub=" rot = Pfarrer*in bzw. Pastor*in im Elternhaus, schwarz = kein Pfarrerskind, 
     weiß = keine Angaben gefunden")

# dieser Plot ist jedoch wahrscheinlich obsolet, da es nur drei gab und somit keine überwältigende Erkenntis entstanden ist

```

```{r Visualisierung des Gesamtnetzwerks der Mitglieder nach Berufsfeldern}

# wir lesen das Gesamtnetzwerk neu ein, sicherheitshalber sollten Environment und Console gereinigt werden

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

raf
list.vertex.attributes(raf)

# Das Vertex-Attribut job definiert, welcher Berufsgruppe die natürlichen Personen angehört haben; 1= Journalist/in, 2= Lehramt/Pädagogik, 3= Jurist/in, 4= sonstige. Im Folgenden sollen die Knoten, bei denen es sich um Personen handelt, je nach ihrer Berufsgruppe unterschiedlich farbig eingefärbt werden.

V(raf)[V(raf)$job == 1]$color <- "blue" # Journalist*innen blau einfärben
V(raf)[V(raf)$job == 2]$color <- "green" # Lehrer*innen etc grün einfärben
V(raf)[V(raf)$job == 3]$color <- "red" # Jurist*innen rot einfärben
V(raf)[V(raf)$job == 4]$color <- "orange" # Sonstige Berufsgruppe orange einfärben
V(raf)[V(raf)$job == 5]$color <- "pink" # Studierende rot einfärben
V(raf)[V(raf)$job == 6]$color <- "black" # Kunstschaffende orange einfärben

# Visualisierung des Gesamtnetzwerks der Mitglieder nach Berufsfeldern
plot(raf, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Netzwerk der ersten und zweiten RAF-Generation nach Berufsfeldern",
     sub="blau = Journalist*innen, grün = Lehrer*innen/Pädadog*innen, rot = Jurist*innen, 
     pink = Student*in, schwarz = Künstler*in, orange = Sonstige")

```

```{r Teilnetzwerk der 1. Generation nach Berufsfeldern}
# Wir lesen hierzu das Netzwerk nochmal neu ein:

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)
raf

# Wir wollen nun wissen, wie das Netzwerk der ersten Generation der RAF aussieht:
raf_eins <- delete_vertices(raf, V(raf)[generation !="1"]) # löscht alle Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der ersten Generation angehört haben. 

#raf_eins <- add.vertices(raf, V(raf)[generation !="3"]) # Da im Codebuch neben Akteuren, die der ersten und zweiten Generation angehört haben, auch Akteure, die beiden Generationen angehört haben, definiert sind, sollen diese dem Netzwerk wieder hinzugefügt werden. Im Schritt zuvor wurden diese ja mit herausgelöscht, da nur Knoten mit dem Wert generation = 1 behalten wurden, aber wer beiden Generationen angehört hat (generation = 1), muss natürlich auch dem Netzwerk der 1. Generation hinzugefügt werden. !! Notiz: eigentlich wichtiger Befehl, aber irgendeinwie plottet es damit gerade nicht, deshalb vorübergehend deaktiviert, bis ich eine Lösung gefunden habe

raf_eins
vertex_attr(raf_eins)

# um das Netzwerk der ersten Generation anzuzeigen, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
raf_eins_mem <- delete_vertices(raf_eins, V(raf_eins)[type !="1"])

raf_eins_mem


V(raf_eins_mem)[V(raf_eins_mem)$job == 1]$color <- "blue" # Journalist*innen blau einfärben
V(raf_eins_mem)[V(raf_eins_mem)$job == 2]$color <- "green" # Lehrer*innen etc grün einfärben
V(raf_eins_mem)[V(raf_eins_mem)$job == 3]$color <- "red" # Jurist*innen rot einfärben
V(raf_eins_mem)[V(raf_eins_mem)$job == 4]$color <- "orange" # Sonstige Berufsgruppe orange einfärben
V(raf_eins_mem)[V(raf_eins_mem)$job == 5]$color <- "pink" # Studierende rot einfärben
V(raf_eins_mem)[V(raf_eins_mem)$job == 6]$color <- "black" # Kunstschaffende orange einfärben

# Visualisierung des Gesamtnetzwerks der Mitglieder nach Berufsfeldern
plot(raf_eins_mem, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_eins_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Netzwerk der ersten RAF-Generation nach Berufsfeldern",
     sub="blau = Journalist*innen, grün = Lehrer*innen/Pädadog*innen, rot = Jurist*innen, 
     pink = Student*in, schwarz = Künstler*in, orange = Sonstige")

```

```{r Teilnetzwerk der ersten und zweiten Generation nach Berufsfeldern}
# gegebenenfalls muss das Netzwerk nochmal neu eingelesen werden, den code findet man beispielsweise zwei Chunks weiter oben. Wenn man jedoch erst environment und console bereinigt und dann die zwei vorherigen Chunks ausführt, bevor man diesen chunk plottet, sollte es auch so funktionieren.

# Wir wollen nun wissen, wie das Netzwerk der zweiten Generation der RAF aussieht:
raf_zwei <- delete_vertices(raf, V(raf)[generation !="2"]) # löscht alle Knoten, für die der Wert von generation nicht 1 beträgt, d.h. die nicht der ersten Generation angehört haben. 

raf_eins <- add.vertices(raf, V(raf)[generation !="3"]) # Da im Codebuch neben Akteuren, die der ersten und zweiten Generation angehört haben, auch Akteure, die beiden Generationen angehört haben, definiert sind, sollen diese dem Netzwerk wieder hinzugefügt werden. Im Schritt zuvor wurden diese ja mit herausgelöscht, da nur Knoten mit dem Wert generation = 1 behalten wurden, aber wer beiden Generationen angehört hat (generation = 1), muss natürlich auch dem Netzwerk der 1. Generation hinzugefügt werden. 

raf_zwei
vertex_attr(raf_zwei)

# um das Netzwerk der zweiten Generation anzuzeigen, sollen nun die Knoten, bei denen es sich um Aktionen und nicht um natürliche Personen handelt, gelöscht werden 
raf_zwei_mem <- delete_vertices(raf_zwei, V(raf_zwei)[type !="1"])

raf_zwei_mem


V(raf_zwei_mem)[V(raf_zwei_mem)$job == 1]$color <- "blue" # Journalist*innen blau einfärben
V(raf_zwei_mem)[V(raf_zwei_mem)$job == 2]$color <- "green" # Lehrer*innen etc grün einfärben
V(raf_zwei_mem)[V(raf_zwei_mem)$job == 3]$color <- "red" # Jurist*innen rot einfärben
V(raf_zwei_mem)[V(raf_zwei_mem)$job == 4]$color <- "orange" # Sonstige Berufsgruppe orange einfärben
V(raf_zwei_mem)[V(raf_zwei_mem)$job == 5]$color <- "pink" # Studierende rot einfärben
V(raf_zwei_mem)[V(raf_zwei_mem)$job == 6]$color <- "black" # Kunstschaffende orange einfärben

# Visualisierung des Gesamtnetzwerks der Mitglieder nach Berufsfeldern
plot(raf_zwei_mem, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_zwei_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Netzwerk der zweiten RAF-Generation nach Berufsfeldern",
     sub="blau = Journalist*innen, grün = Lehrer*innen/Pädadog*innen, rot = Jurist*innen, 
     pink = Student*in, schwarz = Künstler*in, orange = Sonstige")

par(mfrow=c(1,2), mar=c(0,0,2,1)) # definiert, dass zwei Abbildungen in einer Zeile stehen

raf_eins_mem

plot(raf_eins_mem, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_eins_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Erste Generation",
     sub="blau = Journalist*innen, grün = Lehrer*innen/Pädadog*innen, rot = Jurist*innen, 
     pink = Student*in, schwarz = Künstler*in, orange = Sonstige")

plot(raf_zwei_mem, 
     layout=layout_with_kk,
     edge.color="grey",
     edge.arrow.size=.3,
     vertex.size=5,
     edge.curved=curve_multiple(raf_zwei_mem), #sorgt dafür, dass sich keine Kanten überlagern
     vertex.label=NA, #entfernt die Knoten-Beschriftung
     main="Zweite Generation",
     sub="blau = Journalist*innen, grün = Lehrer*innen/Pädadog*innen, rot = Jurist*innen, 
     pink = Student*in, schwarz = Künstler*in, orange = Sonstige")
```

```{r Egonetzwerk Andreas Baader}

# Da in der allgemeinen Bevölkerung Andreas Baader zu den bekanntesten Mitgliedern der RAF zählt, soll sein Ego-Netzwerk generiert werden. 

# Wir lesen das Netzwerk dazu im Folgenden neu ein

# Zunächst werden Edge - und Nodelist eingelesen:
el <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/edges.csv", header=T, as.is=T, sep = ",")
nodes <- read.csv("https://raw.githubusercontent.com/ca048/RAF-Forschungsdesign/master/nodes.csv", header=T, as.is=T, sep = ",")

#Edge- und Nodelist werden zu einer Matrix verknüpft
edgematrix <-as.matrix(el)
raf <- graph_from_data_frame(d=edgematrix, vertices=nodes, directed=FALSE)

raf

# zeigt die Knoten mit den meisten Verbindungen, ähnlich wie der degree Wert.
ego_size(raf)

# Wir stellen fest, dass Knoten 1 (Andreas Baader) die meisten degrees hat. Deshalb wollen wir ein Ego-Netzwerk aus diesem Graph generieren.
degree(raf)

# selektiert aus dem Netzwerk raf alle Knoten, die mit Knoten 1 über einen Schritt verbunden sind.
king <- make_ego_graph(raf, order = 1, nodes = V(raf)$name == "Andreas Baader", mode ="all")

# liefert eine Liste der Verbindungen (in diesem Falle alle out/indgree Beziehungen von Baader)
king

# liefert einen (nicht besonders aufregenden) Plot des selektierten Ego-Netzwerks "king"

# man braucht diesen Zwischenschrit, damit das igraph-Objekt von king1 hergestellt ist
king1 <- king[[1]]
king1

#Grafisch werden Ereignisse/Aktionen  anders dargestellt als Akteure
V(king1)[V(king1)$type == 1]$shape <- "circle" # Personen als Kreise
V(king1)[V(king1)$type == 2]$shape <- "square" # Aktionen als Quadrate
V(king1)[V(king1)$type == 1]$color <- "blue" # Personen blau einfärben
V(king1)[V(king1)$type == 2]$color <- "orange" # Aktionen orange einfärben


V(king1)[V(king1)$name == "Andreas Baader"]$color <- "red" # Baader rot hervorheben

# Nun werden verschiedene Visualisierungsoptionen ausprobiert, um eine möglichst entzerrte Darstellung zu erreichen

l <- layout_with_kk(king1)
l <- norm_coords(l, ymin=-0.8, ymax=.8, xmin=-.8, xmax=.8)

par(mfrow=c(2,2), mar=c(3,3,3,3))
plot(king1, rescale=F, layout=l*0.4)
plot(king1, rescale=F, layout=l*0.8)
plot(king1, rescale=F, layout=l*1.2)
plot(king1, rescale=F, layout=l*1.6)

# Beste Visualisierung ist mit Faktor 1.2
par(mfrow=c(1,1), mar=c(2,2,2,2))

# Nun wird das Egonetzwerk von Baader geplottet
plot(king1,  
     edge.curved=curve_multiple(king1), 
     vertex.label=NA, # Beschriftung der Labels zur besseren Übersicht entfernt
     vertex.size=8,
     rescale=F, 
     layout=l*1.2, 
     main="Ego-Netzwerk Andreas Baader, erster Grad",
     sub="Kreis = Person, Aktion = Quadrat, roter Kreis = Andreas Baader")

```